#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef ZOHODESKPORTALCONFIGURATION_SWIFT_H
#define ZOHODESKPORTALCONFIGURATION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import QuickLook;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZohoDeskPortalConfiguration",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12DPAttachment")
@interface DPAttachment : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12DPBaseBinder")
@interface DPBaseBinder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration16DPBaseListBinder")
@interface DPBaseListBinder : DPBaseBinder
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration24DPAttachmentUploadBinder")
@interface DPAttachmentUploadBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration18DPBaseDetailBinder")
@interface DPBaseDetailBinder : DPBaseBinder
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration15DPConfiguration")
@interface DPConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration20DPGlobalSearchBinder")
@interface DPGlobalSearchBinder : DPBaseDetailBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;
SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration23DPInternalThemeProtocol_")
@protocol DPInternalThemeProtocol
@property (nonatomic, readonly, strong) UIColor * _Nonnull themeColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull iconColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull borderColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull separatorColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull selectedColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull failureColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull searchBGColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentTextSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGUnselected;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12DPMenuBinder")
@interface DPMenuBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
@class NSString;
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13DPPreviewItem")
@interface DPPreviewItem : NSObject <QLPreviewItem>
@property (nonatomic, copy) NSURL * _Nullable previewItemURL;
@property (nonatomic, copy) NSString * _Nullable previewItemTitle;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration10DPProvider")
@interface DPProvider : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration20LanguagePickerBinder")
@interface LanguagePickerBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SearchCounter object for search result’s count and focused index
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13SearchCounter")
@interface SearchCounter : NSObject
@property (nonatomic, readonly) NSInteger totalCount;
@property (nonatomic, readonly) NSInteger currentIndex;
+ (nullable instancetype)prepareInstanceFrom:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
@end

/// SearchLocator object to address focused search item’s onscreen location
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13SearchLocator")
@interface SearchLocator : NSObject
@property (nonatomic, readonly) CGRect rect;
+ (nullable instancetype)prepareInstanceFrom:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
@end

@protocol ZDPAnalyticsDelegate;
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12ZDPAnalytics")
@interface ZDPAnalytics : NSObject
@property (nonatomic, weak) id <ZDPAnalyticsDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZDPAnalytics * _Nonnull shared;)
+ (ZDPAnalytics * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(ZDPAnalytics * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ZDPortalUIAction : NSInteger;
SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration20ZDPAnalyticsDelegate_")
@protocol ZDPAnalyticsDelegate
- (void)handleZDPEventsWithEventName:(enum ZDPortalUIAction)eventName withData:(NSDictionary<NSString *, id> * _Nullable)eventData;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration16ZDPConfiguration")
@interface ZDPConfiguration : NSObject
@property (nonatomic) BOOL disableSidemenu;
@property (nonatomic) BOOL disableLanguageChooser;
@property (nonatomic) BOOL disablePoweredByZoho;
@property (nonatomic) BOOL disableGlobalSearch;
@property (nonatomic) BOOL disableKB;
@property (nonatomic) BOOL disableCommunity;
@property (nonatomic) BOOL disableAddTopic;
@property (nonatomic) BOOL disableMyTicket;
@property (nonatomic) BOOL disableSubmitTicket;
@property (nonatomic) BOOL disableGC;
@property (nonatomic) BOOL disableAnswerBot;
@property (nonatomic) BOOL disableBM;
@property (nonatomic) BOOL disableChat;
@property (nonatomic) BOOL enableModuleBasedSearch;
@property (nonatomic) BOOL disableNavigationBottomLine;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDPEventProperties, open) {
  ZDPEventPropertiesEventScreen = 0,
  ZDPEventPropertiesEventSource = 1,
  ZDPEventPropertiesItemData = 2,
};

typedef SWIFT_ENUM(NSInteger, ZDPLanguageChangeScreen, open) {
  ZDPLanguageChangeScreenDashboard = 0,
  ZDPLanguageChangeScreenKbRootCategories = 1,
  ZDPLanguageChangeScreenKbArticleDetail = 2,
};

typedef SWIFT_ENUM(NSInteger, ZDPNavigationMode, open) {
  ZDPNavigationModePush = 0,
  ZDPNavigationModePresent = 1,
};

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration23ZDPPrivacyConfiguration")
@interface ZDPPrivacyConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration14ZDPReplyBinder")
@interface ZDPReplyBinder : DPBaseBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration29ZDPSecureContentConfiguration")
@interface ZDPSecureContentConfiguration : NSObject
@property (nonatomic) BOOL disableDownloadAttachment;
@property (nonatomic) BOOL disableUploadAttachment;
@property (nonatomic) BOOL disableScreenShot;
@property (nonatomic) BOOL disableCopyPaste;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVSpeechSynthesizer;
@class AVSpeechUtterance;
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration15ZDPSpeechWriter")
@interface ZDPSpeechWriter : NSObject <AVSpeechSynthesizerDelegate>
/// Notified once the speech to audio conversion completed
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didFinishSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13ZDPTextReader")
@interface ZDPTextReader : NSObject <AVSpeechSynthesizerDelegate>
/// Delegate func notified when speech begin
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didStartSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
/// Delegate func notified when speech finish and cancelled
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didFinishSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
/// Few of the earlier version uses didCancel delegate method for stopspeaking action
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didCancelSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
/// Notified for current reading word range
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer willSpeakRangeOfSpeechString:(NSRange)characterRange utterance:(AVSpeechUtterance * _Nonnull)utterance;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ZDPThemeType : NSInteger;
@protocol ZDPThemeProtocol;
/// Theme manager of the Zoho Desk Portal SDK you can customize SDK color using this class.
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration15ZDPThemeManager")
@interface ZDPThemeManager : NSObject
/// Setting theme for SDK
/// \param theme Type of theme possible values are Dark, Light, System.
///
+ (void)setThemeWithType:(enum ZDPThemeType)theme;
/// Customize the Light theme.
/// \param theme Customized color values for LightTheme.
///
+ (void)updateLightThemeWithTheme:(id <ZDPThemeProtocol> _Nonnull)theme;
/// Customize the Dark theme.
/// \param theme Customized color values for DarkTheme.
///
+ (void)updateDarkThemeWithTheme:(id <ZDPThemeProtocol> _Nonnull)theme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration16ZDPThemeProtocol_")
@protocol ZDPThemeProtocol
@optional
@property (nonatomic, readonly, strong) UIColor * _Nonnull themeColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull iconColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull borderColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull separatorColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull selectedColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull failureColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull searchBGColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentTextSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGUnselected;
@end

typedef SWIFT_ENUM(NSInteger, ZDPThemeType, open) {
/// Light theme
  ZDPThemeTypeLight = 0,
/// Dark Theme
  ZDPThemeTypeDark = 1,
/// System theme available from iOS13
  ZDPThemeTypeSystem = 2,
};

typedef SWIFT_ENUM(NSInteger, ZDPViewController, open) {
  ZDPViewControllerDashBoard = 0,
  ZDPViewControllerKBCategoryList = 1,
  ZDPViewControllerKBArticleDetail = 2,
  ZDPViewControllerCreateTicket = 3,
  ZDPViewControllerCommunityCatagories = 4,
  ZDPViewControllerCommunityTopics = 5,
  ZDPViewControllerCommunityTopicDetail = 6,
  ZDPViewControllerMyTicketList = 7,
  ZDPViewControllerChat = 8,
};

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration21ZDPortalConfiguration")
@interface ZDPortalConfiguration : NSObject
+ (void)processRemoteNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo;
+ (void)setSDKLanguage:(NSString * _Nonnull)languageCode;
+ (void)setWithConfiguration:(ZDPConfiguration * _Nonnull)configuration;
+ (void)setZDPSecureConfigurationWithConfiguration:(ZDPSecureContentConfiguration * _Nonnull)configuration;
+ (void)setChatBrandDetailsWithAppKey:(NSString * _Nonnull)appKey accessKey:(NSString * _Nonnull)accessKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ZDPortalDelegate;
@interface ZDPortalConfiguration (SWIFT_EXTENSION(ZohoDeskPortalConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull customFontName;)
+ (NSString * _Nonnull)customFontName SWIFT_WARN_UNUSED_RESULT;
+ (void)setCustomFontName:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum ZDPNavigationMode navigationMode;)
+ (enum ZDPNavigationMode)navigationMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setNavigationMode:(enum ZDPNavigationMode)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL prefersLargeTitle;)
+ (BOOL)prefersLargeTitle SWIFT_WARN_UNUSED_RESULT;
+ (void)setPrefersLargeTitle:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL pushOnActiveState;)
+ (BOOL)pushOnActiveState SWIFT_WARN_UNUSED_RESULT;
+ (void)setPushOnActiveState:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) UIModalPresentationStyle modalPresentationStyle;)
+ (UIModalPresentationStyle)modalPresentationStyle SWIFT_WARN_UNUSED_RESULT;
+ (void)setModalPresentationStyle:(UIModalPresentationStyle)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableSwipeToPopGesture;)
+ (BOOL)enableSwipeToPopGesture SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableSwipeToPopGesture:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id <ZDPortalDelegate> _Nullable delegate;)
+ (id <ZDPortalDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <ZDPortalDelegate> _Nullable)value;
@end

typedef SWIFT_ENUM(NSInteger, ZDPortalControllers, open) {
  ZDPortalControllersDashBoard = 0,
  ZDPortalControllersSideMenu = 1,
  ZDPortalControllersLanguageList = 2,
  ZDPortalControllersGlobal_Search = 3,
  ZDPortalControllersKBCategoryList = 4,
  ZDPortalControllersKBChildCategoryList = 5,
  ZDPortalControllersKBPopularArticles = 6,
  ZDPortalControllersKBRecentArticles = 7,
  ZDPortalControllersKBArticleList = 8,
  ZDPortalControllersKBArticleDetail = 9,
  ZDPortalControllersKBPreviousNextArticles = 10,
  ZDPortalControllersKBRelatedArticles = 11,
  ZDPortalControllersKBTagsList = 12,
  ZDPortalControllersFeedBack = 13,
  ZDPortalControllersKBDeeplinking = 14,
  ZDPortalControllersNil = 15,
  ZDPortalControllersTopicIDDeeplinking = 16,
  ZDPortalControllersTopicTypeDeeplinking = 17,
  ZDPortalControllersCYTopicFilter = 18,
  ZDPortalControllersCYFilterList = 19,
  ZDPortalControllersCYTopicSort = 20,
  ZDPortalControllersCYCategories = 21,
  ZDPortalControllersCYForums = 22,
  ZDPortalControllersCYTopicsList = 23,
  ZDPortalControllersCYRecentTopicsList = 24,
  ZDPortalControllersCYAnnouncementTopicsList = 25,
  ZDPortalControllersCYStickyTopicsList = 26,
  ZDPortalControllersCYTagsTopicsList = 27,
  ZDPortalControllersCYMostDiscussedTopics = 28,
  ZDPortalControllersCYStickyPosts = 29,
  ZDPortalControllersCYAnnouncementTopics = 30,
  ZDPortalControllersCYTopicDetail = 31,
  ZDPortalControllersCYCreateTopic = 32,
  ZDPortalControllersCYTopicReply = 33,
  ZDPortalControllersAttachmentList = 34,
  ZDPortalControllersTicketsSort = 35,
  ZDPortalControllersTicketsList = 36,
  ZDPortalControllersEmptyTicketsUI = 37,
  ZDPortalControllersTicketsConversation = 38,
  ZDPortalControllersTicketForm = 39,
  ZDPortalControllersTicketProperties = 40,
  ZDPortalControllersAddTicketDepartmentList = 41,
  ZDPortalControllersAddTicketLayoutList = 42,
};

SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration16ZDPortalDelegate_")
@protocol ZDPortalDelegate
@optional
- (void)dismissedWithViewController:(enum ZDPViewController)viewController;
- (void)languageChangedTo:(NSString * _Nonnull)languageIdentifier in:(enum ZDPLanguageChangeScreen)screen;
@end

typedef SWIFT_ENUM(NSInteger, ZDPortalUIAction, open) {
  ZDPortalUIActionLanguageChanged = 0,
  ZDPortalUIActionKBSearchedArticleClicked = 1,
  ZDPortalUIActionKBCategoryClicked = 2,
  ZDPortalUIActionKBChildCategoryClicked = 3,
  ZDPortalUIActionKBArticleClicked = 4,
  ZDPortalUIActionKBArticleUpVoted = 5,
  ZDPortalUIActionKBArticleDownVoted = 6,
  ZDPortalUIActionKBCommentClicked = 7,
  ZDPortalUIActionKBArticleShare = 8,
  ZDPortalUIActionAttachmentPreviewClick = 9,
  ZDPortalUIActionAttachmentDownloadClick = 10,
  ZDPortalUIActionArticleTagClick = 11,
  ZDPortalUIActionKBArticleFeedBackSent = 12,
  ZDPortalUIActionKBArticleFeedBackSkip = 13,
  ZDPortalUIActionKBArticleDeeplinking = 14,
  ZDPortalUIActionKBCategoryDeeplinking = 15,
  ZDPortalUIActionKBArticleNotAvailable = 16,
  ZDPortalUIActionKBCategoryNotAvailable = 17,
  ZDPortalUIActionKBArticleListenClick = 18,
  ZDPortalUIActionNil = 19,
  ZDPortalUIActionCYSearchedTopicClicked = 20,
  ZDPortalUIActionCYTopicClicked = 21,
  ZDPortalUIActionCYSearchFilterSelection = 22,
  ZDPortalUIActionCYFilterSelection = 23,
  ZDPortalUIActionCYCategoryClicked = 24,
  ZDPortalUIActionCYForumClicked = 25,
  ZDPortalUIActionCYCategoryFollow = 26,
  ZDPortalUIActionCYCategoryUnFollow = 27,
  ZDPortalUIActionCYFollowersClick = 28,
  ZDPortalUIActionCYTopicFollow = 29,
  ZDPortalUIActionCYTopicUnFollow = 30,
  ZDPortalUIActionCYTopicLiked = 31,
  ZDPortalUIActionCYTopicShare = 32,
  ZDPortalUIActionCYReplyClick = 33,
  ZDPortalUIActionCYRelatedArticleClicked = 34,
  ZDPortalUIActionCYParticipantsClicked = 35,
  ZDPortalUIActionCYTopicTagClicked = 36,
  ZDPortalUIActionCYTopicEdited = 37,
  ZDPortalUIActionCYTopicCreated = 38,
  ZDPortalUIActionCYTopicDeleted = 39,
  ZDPortalUIActionCYTopicReplyAction = 40,
  ZDPortalUIActionCYTopicReplyEdit = 41,
  ZDPortalUIActionCYTopicReplyDelete = 42,
  ZDPortalUIActionCYTopicCommentAction = 43,
  ZDPortalUIActionCYTopicCommentEdit = 44,
  ZDPortalUIActionCYTopicCommentDelete = 45,
  ZDPortalUIActionCYTopicPreviewAction = 46,
  ZDPortalUIActionCYTopicSavedAsDraft = 47,
  ZDPortalUIActionCYDraftDeleted = 48,
  ZDPortalUIActionCYDraftSelected = 49,
  ZDPortalUIActionAttachmentUpload = 50,
  ZDPortalUIActionAttachmentDelete = 51,
  ZDPortalUIActionCYTopicDeeplinking = 52,
  ZDPortalUIActionCYTopicsDeeplinking = 53,
  ZDPortalUIActionCYCategoryDeeplinking = 54,
  ZDPortalUIActionCYTopicFormClick = 55,
  ZDPortalUIActionCYTopicListenClick = 56,
  ZDPortalUIActionTicketsDetailClick = 57,
  ZDPortalUIActionTicketsSearchClick = 58,
  ZDPortalUIActionTicketsSubmitTicketClick = 59,
  ZDPortalUIActionTicketsFilterClick = 60,
  ZDPortalUIActionTicketsReplyAdd = 61,
  ZDPortalUIActionTicketsCommentAdd = 62,
  ZDPortalUIActionTicketsCommentEdit = 63,
  ZDPortalUIActionTicketsDraftAdd = 64,
  ZDPortalUIActionTicketsDraftEdit = 65,
  ZDPortalUIActionTicketsCommentDelete = 66,
  ZDPortalUIActionTicketsClose = 67,
  ZDPortalUIActionTicketsEdit = 68,
  ZDPortalUIActionAddTicketDepartmentClick = 69,
  ZDPortalUIActionAddTicketLayoutClick = 70,
  ZDPortalUIActionAddTicketSendClick = 71,
  ZDPortalUIActionAddTicketSendCancel = 72,
};

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration14ZPPickerBinder")
@interface ZPPickerBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration20ZPPickerSearchBinder")
@interface ZPPickerSearchBinder : ZPPickerBinder
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef ZOHODESKPORTALCONFIGURATION_SWIFT_H
#define ZOHODESKPORTALCONFIGURATION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import QuickLook;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZohoDeskPortalConfiguration",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12DPAttachment")
@interface DPAttachment : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12DPBaseBinder")
@interface DPBaseBinder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration16DPBaseListBinder")
@interface DPBaseListBinder : DPBaseBinder
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration24DPAttachmentUploadBinder")
@interface DPAttachmentUploadBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration18DPBaseDetailBinder")
@interface DPBaseDetailBinder : DPBaseBinder
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration15DPConfiguration")
@interface DPConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration20DPGlobalSearchBinder")
@interface DPGlobalSearchBinder : DPBaseDetailBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;
SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration23DPInternalThemeProtocol_")
@protocol DPInternalThemeProtocol
@property (nonatomic, readonly, strong) UIColor * _Nonnull themeColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull iconColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull borderColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull separatorColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull selectedColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull failureColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull searchBGColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentTextSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGUnselected;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12DPMenuBinder")
@interface DPMenuBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;
@class NSString;
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13DPPreviewItem")
@interface DPPreviewItem : NSObject <QLPreviewItem>
@property (nonatomic, copy) NSURL * _Nullable previewItemURL;
@property (nonatomic, copy) NSString * _Nullable previewItemTitle;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration10DPProvider")
@interface DPProvider : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration20LanguagePickerBinder")
@interface LanguagePickerBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SearchCounter object for search result’s count and focused index
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13SearchCounter")
@interface SearchCounter : NSObject
@property (nonatomic, readonly) NSInteger totalCount;
@property (nonatomic, readonly) NSInteger currentIndex;
+ (nullable instancetype)prepareInstanceFrom:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
@end

/// SearchLocator object to address focused search item’s onscreen location
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13SearchLocator")
@interface SearchLocator : NSObject
@property (nonatomic, readonly) CGRect rect;
+ (nullable instancetype)prepareInstanceFrom:(NSDictionary<NSString *, id> * _Nonnull)dictionary SWIFT_WARN_UNUSED_RESULT;
@end

@protocol ZDPAnalyticsDelegate;
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration12ZDPAnalytics")
@interface ZDPAnalytics : NSObject
@property (nonatomic, weak) id <ZDPAnalyticsDelegate> _Nullable delegate;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZDPAnalytics * _Nonnull shared;)
+ (ZDPAnalytics * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(ZDPAnalytics * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ZDPortalUIAction : NSInteger;
SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration20ZDPAnalyticsDelegate_")
@protocol ZDPAnalyticsDelegate
- (void)handleZDPEventsWithEventName:(enum ZDPortalUIAction)eventName withData:(NSDictionary<NSString *, id> * _Nullable)eventData;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration16ZDPConfiguration")
@interface ZDPConfiguration : NSObject
@property (nonatomic) BOOL disableSidemenu;
@property (nonatomic) BOOL disableLanguageChooser;
@property (nonatomic) BOOL disablePoweredByZoho;
@property (nonatomic) BOOL disableGlobalSearch;
@property (nonatomic) BOOL disableKB;
@property (nonatomic) BOOL disableCommunity;
@property (nonatomic) BOOL disableAddTopic;
@property (nonatomic) BOOL disableMyTicket;
@property (nonatomic) BOOL disableSubmitTicket;
@property (nonatomic) BOOL disableGC;
@property (nonatomic) BOOL disableAnswerBot;
@property (nonatomic) BOOL disableBM;
@property (nonatomic) BOOL disableChat;
@property (nonatomic) BOOL enableModuleBasedSearch;
@property (nonatomic) BOOL disableNavigationBottomLine;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDPEventProperties, open) {
  ZDPEventPropertiesEventScreen = 0,
  ZDPEventPropertiesEventSource = 1,
  ZDPEventPropertiesItemData = 2,
};

typedef SWIFT_ENUM(NSInteger, ZDPLanguageChangeScreen, open) {
  ZDPLanguageChangeScreenDashboard = 0,
  ZDPLanguageChangeScreenKbRootCategories = 1,
  ZDPLanguageChangeScreenKbArticleDetail = 2,
};

typedef SWIFT_ENUM(NSInteger, ZDPNavigationMode, open) {
  ZDPNavigationModePush = 0,
  ZDPNavigationModePresent = 1,
};

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration23ZDPPrivacyConfiguration")
@interface ZDPPrivacyConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration14ZDPReplyBinder")
@interface ZDPReplyBinder : DPBaseBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration29ZDPSecureContentConfiguration")
@interface ZDPSecureContentConfiguration : NSObject
@property (nonatomic) BOOL disableDownloadAttachment;
@property (nonatomic) BOOL disableUploadAttachment;
@property (nonatomic) BOOL disableScreenShot;
@property (nonatomic) BOOL disableCopyPaste;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVSpeechSynthesizer;
@class AVSpeechUtterance;
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration15ZDPSpeechWriter")
@interface ZDPSpeechWriter : NSObject <AVSpeechSynthesizerDelegate>
/// Notified once the speech to audio conversion completed
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didFinishSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration13ZDPTextReader")
@interface ZDPTextReader : NSObject <AVSpeechSynthesizerDelegate>
/// Delegate func notified when speech begin
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didStartSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
/// Delegate func notified when speech finish and cancelled
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didFinishSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
/// Few of the earlier version uses didCancel delegate method for stopspeaking action
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer didCancelSpeechUtterance:(AVSpeechUtterance * _Nonnull)utterance;
/// Notified for current reading word range
- (void)speechSynthesizer:(AVSpeechSynthesizer * _Nonnull)synthesizer willSpeakRangeOfSpeechString:(NSRange)characterRange utterance:(AVSpeechUtterance * _Nonnull)utterance;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ZDPThemeType : NSInteger;
@protocol ZDPThemeProtocol;
/// Theme manager of the Zoho Desk Portal SDK you can customize SDK color using this class.
SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration15ZDPThemeManager")
@interface ZDPThemeManager : NSObject
/// Setting theme for SDK
/// \param theme Type of theme possible values are Dark, Light, System.
///
+ (void)setThemeWithType:(enum ZDPThemeType)theme;
/// Customize the Light theme.
/// \param theme Customized color values for LightTheme.
///
+ (void)updateLightThemeWithTheme:(id <ZDPThemeProtocol> _Nonnull)theme;
/// Customize the Dark theme.
/// \param theme Customized color values for DarkTheme.
///
+ (void)updateDarkThemeWithTheme:(id <ZDPThemeProtocol> _Nonnull)theme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration16ZDPThemeProtocol_")
@protocol ZDPThemeProtocol
@optional
@property (nonatomic, readonly, strong) UIColor * _Nonnull themeColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull primaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull secondaryTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull iconColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull borderColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull separatorColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull selectedColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarBackgroundColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarTextColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull navigationBarButtonColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull failureColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull searchBGColor;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentTextSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGSelected;
@property (nonatomic, readonly, strong) UIColor * _Nonnull UISegmentBGUnselected;
@end

typedef SWIFT_ENUM(NSInteger, ZDPThemeType, open) {
/// Light theme
  ZDPThemeTypeLight = 0,
/// Dark Theme
  ZDPThemeTypeDark = 1,
/// System theme available from iOS13
  ZDPThemeTypeSystem = 2,
};

typedef SWIFT_ENUM(NSInteger, ZDPViewController, open) {
  ZDPViewControllerDashBoard = 0,
  ZDPViewControllerKBCategoryList = 1,
  ZDPViewControllerKBArticleDetail = 2,
  ZDPViewControllerCreateTicket = 3,
  ZDPViewControllerCommunityCatagories = 4,
  ZDPViewControllerCommunityTopics = 5,
  ZDPViewControllerCommunityTopicDetail = 6,
  ZDPViewControllerMyTicketList = 7,
  ZDPViewControllerChat = 8,
};

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration21ZDPortalConfiguration")
@interface ZDPortalConfiguration : NSObject
+ (void)processRemoteNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo;
+ (void)setSDKLanguage:(NSString * _Nonnull)languageCode;
+ (void)setWithConfiguration:(ZDPConfiguration * _Nonnull)configuration;
+ (void)setZDPSecureConfigurationWithConfiguration:(ZDPSecureContentConfiguration * _Nonnull)configuration;
+ (void)setChatBrandDetailsWithAppKey:(NSString * _Nonnull)appKey accessKey:(NSString * _Nonnull)accessKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ZDPortalDelegate;
@interface ZDPortalConfiguration (SWIFT_EXTENSION(ZohoDeskPortalConfiguration))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull customFontName;)
+ (NSString * _Nonnull)customFontName SWIFT_WARN_UNUSED_RESULT;
+ (void)setCustomFontName:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum ZDPNavigationMode navigationMode;)
+ (enum ZDPNavigationMode)navigationMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setNavigationMode:(enum ZDPNavigationMode)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL prefersLargeTitle;)
+ (BOOL)prefersLargeTitle SWIFT_WARN_UNUSED_RESULT;
+ (void)setPrefersLargeTitle:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL pushOnActiveState;)
+ (BOOL)pushOnActiveState SWIFT_WARN_UNUSED_RESULT;
+ (void)setPushOnActiveState:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) UIModalPresentationStyle modalPresentationStyle;)
+ (UIModalPresentationStyle)modalPresentationStyle SWIFT_WARN_UNUSED_RESULT;
+ (void)setModalPresentationStyle:(UIModalPresentationStyle)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableSwipeToPopGesture;)
+ (BOOL)enableSwipeToPopGesture SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableSwipeToPopGesture:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id <ZDPortalDelegate> _Nullable delegate;)
+ (id <ZDPortalDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setDelegate:(id <ZDPortalDelegate> _Nullable)value;
@end

typedef SWIFT_ENUM(NSInteger, ZDPortalControllers, open) {
  ZDPortalControllersDashBoard = 0,
  ZDPortalControllersSideMenu = 1,
  ZDPortalControllersLanguageList = 2,
  ZDPortalControllersGlobal_Search = 3,
  ZDPortalControllersKBCategoryList = 4,
  ZDPortalControllersKBChildCategoryList = 5,
  ZDPortalControllersKBPopularArticles = 6,
  ZDPortalControllersKBRecentArticles = 7,
  ZDPortalControllersKBArticleList = 8,
  ZDPortalControllersKBArticleDetail = 9,
  ZDPortalControllersKBPreviousNextArticles = 10,
  ZDPortalControllersKBRelatedArticles = 11,
  ZDPortalControllersKBTagsList = 12,
  ZDPortalControllersFeedBack = 13,
  ZDPortalControllersKBDeeplinking = 14,
  ZDPortalControllersNil = 15,
  ZDPortalControllersTopicIDDeeplinking = 16,
  ZDPortalControllersTopicTypeDeeplinking = 17,
  ZDPortalControllersCYTopicFilter = 18,
  ZDPortalControllersCYFilterList = 19,
  ZDPortalControllersCYTopicSort = 20,
  ZDPortalControllersCYCategories = 21,
  ZDPortalControllersCYForums = 22,
  ZDPortalControllersCYTopicsList = 23,
  ZDPortalControllersCYRecentTopicsList = 24,
  ZDPortalControllersCYAnnouncementTopicsList = 25,
  ZDPortalControllersCYStickyTopicsList = 26,
  ZDPortalControllersCYTagsTopicsList = 27,
  ZDPortalControllersCYMostDiscussedTopics = 28,
  ZDPortalControllersCYStickyPosts = 29,
  ZDPortalControllersCYAnnouncementTopics = 30,
  ZDPortalControllersCYTopicDetail = 31,
  ZDPortalControllersCYCreateTopic = 32,
  ZDPortalControllersCYTopicReply = 33,
  ZDPortalControllersAttachmentList = 34,
  ZDPortalControllersTicketsSort = 35,
  ZDPortalControllersTicketsList = 36,
  ZDPortalControllersEmptyTicketsUI = 37,
  ZDPortalControllersTicketsConversation = 38,
  ZDPortalControllersTicketForm = 39,
  ZDPortalControllersTicketProperties = 40,
  ZDPortalControllersAddTicketDepartmentList = 41,
  ZDPortalControllersAddTicketLayoutList = 42,
};

SWIFT_PROTOCOL("_TtP27ZohoDeskPortalConfiguration16ZDPortalDelegate_")
@protocol ZDPortalDelegate
@optional
- (void)dismissedWithViewController:(enum ZDPViewController)viewController;
- (void)languageChangedTo:(NSString * _Nonnull)languageIdentifier in:(enum ZDPLanguageChangeScreen)screen;
@end

typedef SWIFT_ENUM(NSInteger, ZDPortalUIAction, open) {
  ZDPortalUIActionLanguageChanged = 0,
  ZDPortalUIActionKBSearchedArticleClicked = 1,
  ZDPortalUIActionKBCategoryClicked = 2,
  ZDPortalUIActionKBChildCategoryClicked = 3,
  ZDPortalUIActionKBArticleClicked = 4,
  ZDPortalUIActionKBArticleUpVoted = 5,
  ZDPortalUIActionKBArticleDownVoted = 6,
  ZDPortalUIActionKBCommentClicked = 7,
  ZDPortalUIActionKBArticleShare = 8,
  ZDPortalUIActionAttachmentPreviewClick = 9,
  ZDPortalUIActionAttachmentDownloadClick = 10,
  ZDPortalUIActionArticleTagClick = 11,
  ZDPortalUIActionKBArticleFeedBackSent = 12,
  ZDPortalUIActionKBArticleFeedBackSkip = 13,
  ZDPortalUIActionKBArticleDeeplinking = 14,
  ZDPortalUIActionKBCategoryDeeplinking = 15,
  ZDPortalUIActionKBArticleNotAvailable = 16,
  ZDPortalUIActionKBCategoryNotAvailable = 17,
  ZDPortalUIActionKBArticleListenClick = 18,
  ZDPortalUIActionNil = 19,
  ZDPortalUIActionCYSearchedTopicClicked = 20,
  ZDPortalUIActionCYTopicClicked = 21,
  ZDPortalUIActionCYSearchFilterSelection = 22,
  ZDPortalUIActionCYFilterSelection = 23,
  ZDPortalUIActionCYCategoryClicked = 24,
  ZDPortalUIActionCYForumClicked = 25,
  ZDPortalUIActionCYCategoryFollow = 26,
  ZDPortalUIActionCYCategoryUnFollow = 27,
  ZDPortalUIActionCYFollowersClick = 28,
  ZDPortalUIActionCYTopicFollow = 29,
  ZDPortalUIActionCYTopicUnFollow = 30,
  ZDPortalUIActionCYTopicLiked = 31,
  ZDPortalUIActionCYTopicShare = 32,
  ZDPortalUIActionCYReplyClick = 33,
  ZDPortalUIActionCYRelatedArticleClicked = 34,
  ZDPortalUIActionCYParticipantsClicked = 35,
  ZDPortalUIActionCYTopicTagClicked = 36,
  ZDPortalUIActionCYTopicEdited = 37,
  ZDPortalUIActionCYTopicCreated = 38,
  ZDPortalUIActionCYTopicDeleted = 39,
  ZDPortalUIActionCYTopicReplyAction = 40,
  ZDPortalUIActionCYTopicReplyEdit = 41,
  ZDPortalUIActionCYTopicReplyDelete = 42,
  ZDPortalUIActionCYTopicCommentAction = 43,
  ZDPortalUIActionCYTopicCommentEdit = 44,
  ZDPortalUIActionCYTopicCommentDelete = 45,
  ZDPortalUIActionCYTopicPreviewAction = 46,
  ZDPortalUIActionCYTopicSavedAsDraft = 47,
  ZDPortalUIActionCYDraftDeleted = 48,
  ZDPortalUIActionCYDraftSelected = 49,
  ZDPortalUIActionAttachmentUpload = 50,
  ZDPortalUIActionAttachmentDelete = 51,
  ZDPortalUIActionCYTopicDeeplinking = 52,
  ZDPortalUIActionCYTopicsDeeplinking = 53,
  ZDPortalUIActionCYCategoryDeeplinking = 54,
  ZDPortalUIActionCYTopicFormClick = 55,
  ZDPortalUIActionCYTopicListenClick = 56,
  ZDPortalUIActionTicketsDetailClick = 57,
  ZDPortalUIActionTicketsSearchClick = 58,
  ZDPortalUIActionTicketsSubmitTicketClick = 59,
  ZDPortalUIActionTicketsFilterClick = 60,
  ZDPortalUIActionTicketsReplyAdd = 61,
  ZDPortalUIActionTicketsCommentAdd = 62,
  ZDPortalUIActionTicketsCommentEdit = 63,
  ZDPortalUIActionTicketsDraftAdd = 64,
  ZDPortalUIActionTicketsDraftEdit = 65,
  ZDPortalUIActionTicketsCommentDelete = 66,
  ZDPortalUIActionTicketsClose = 67,
  ZDPortalUIActionTicketsEdit = 68,
  ZDPortalUIActionAddTicketDepartmentClick = 69,
  ZDPortalUIActionAddTicketLayoutClick = 70,
  ZDPortalUIActionAddTicketSendClick = 71,
  ZDPortalUIActionAddTicketSendCancel = 72,
};

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration14ZPPickerBinder")
@interface ZPPickerBinder : DPBaseListBinder
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC27ZohoDeskPortalConfiguration20ZPPickerSearchBinder")
@interface ZPPickerSearchBinder : ZPPickerBinder
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
