// Generated by Apple Swift version 4.0 effective-3.2 (swiftlang-900.0.65 clang-900.0.37)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreData;
@import QuartzCore;
@import ObjectiveC;
@import Foundation;
@import UIKit;
@import QuickLook;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("ZohoDeskSDK")
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS("_TtC11ZohoDeskSDK11Attachments")
@interface Attachments : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;
@class Solutions;
@class Threads;
@class TicketComment;
@class TopicComments;
@class Topics;

@interface Attachments (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable filePath;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable size;
@property (nonatomic, strong) NSDate * _Nullable modifiedTimeDate;
@property (nonatomic, strong) Solutions * _Nullable solution;
@property (nonatomic, strong) Threads * _Nullable thread;
@property (nonatomic, strong) TicketComment * _Nullable ticketComments;
@property (nonatomic, strong) TopicComments * _Nullable topicComments;
@property (nonatomic, strong) Topics * _Nullable topics;
@end






SWIFT_CLASS("_TtC11ZohoDeskSDK8Catagory")
@interface Catagory : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;

@interface Catagory (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addSolutionsObject:(Solutions * _Nonnull)value;
- (void)removeSolutionsObject:(Solutions * _Nonnull)value;
- (void)addSolutions:(NSSet * _Nonnull)values;
- (void)removeSolutions:(NSSet * _Nonnull)values;
@end

@class Department;

@interface Catagory (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable articleCount;
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable level;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable parentCategoryId;
@property (nonatomic, strong) Department * _Nullable department;
@property (nonatomic, strong) NSSet * _Nullable solutions;
@end


/// ChatActivityHandler is a NSObject class which contains the event handler methods.
SWIFT_CLASS("_TtC11ZohoDeskSDK19ChatActivityHandler")
@interface ChatActivityHandler : NSObject
/// This event handler allows you to invoke a method when the visitor enters/exits the chat window.
/// \param isinternal - Boolean determines whether visitor internal or close the chat window
///
- (void)handleWidgetActionWithIsOpen:(BOOL)isOpen;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK9Community")
@interface Community : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Community (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable commentCount;
@property (nonatomic, copy) NSString * _Nullable descriptionString;
@property (nonatomic, copy) NSString * _Nullable followersCount;
@property (nonatomic, copy) NSString * _Nullable forumCount;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable parentCategoryId;
@property (nonatomic, copy) NSString * _Nullable photoUrl;
@property (nonatomic, copy) NSString * _Nullable postCount;
@property (nonatomic) BOOL isFollow;
@property (nonatomic) BOOL isLocked;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK8Contacts")
@interface Contacts : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Contacts (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable accountId;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable customFields;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable facebook;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable mobile;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nullable ownerId;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable secondaryEmail;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable twitter;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK12CustomFields")
@interface CustomFields : NSObject
@property (nonatomic, copy) NSString * _Nonnull fieldID;
@property (nonatomic, copy) NSString * _Nonnull value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC11ZohoDeskSDK10Department")
@interface Department : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Product;

@interface Department (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addProductObject:(Product * _Nonnull)value;
- (void)removeProductObject:(Product * _Nonnull)value;
- (void)addProduct:(NSSet * _Nonnull)values;
- (void)removeProduct:(NSSet * _Nonnull)values;
@end


@interface Department (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addCatagoryObject:(Catagory * _Nonnull)value;
- (void)removeCatagoryObject:(Catagory * _Nonnull)value;
- (void)addCatagory:(NSSet * _Nonnull)values;
- (void)removeCatagory:(NSSet * _Nonnull)values;
@end

@class TicketFields;

@interface Department (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addTicketFieldsObject:(TicketFields * _Nonnull)value;
- (void)removeTicketFieldsObject:(TicketFields * _Nonnull)value;
- (void)addTicketFields:(NSSet * _Nonnull)values;
- (void)removeTicketFields:(NSSet * _Nonnull)values;
@end


@interface Department (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable descriptionString;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable nameInCustomerPortal;
@property (nonatomic, copy) NSString * _Nullable photoURL;
@property (nonatomic, strong) NSSet * _Nullable catagory;
@property (nonatomic, strong) NSSet * _Nullable product;
@property (nonatomic, strong) NSSet * _Nullable ticketFields;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK20DepartmentJsonObject")
@interface DepartmentJsonObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull photoURL;
@property (nonatomic, copy) NSString * _Nonnull departmentId;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull nameInCustomerPortal;
@property (nonatomic, copy) NSString * _Nonnull descriptionString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC11ZohoDeskSDK17InitialController")
@interface InitialController : UIViewController
- (void)showHelpCenterController;
- (void)showAddTicketController;
- (void)showCommunity;
- (void)showDashBoard;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end






















SWIFT_CLASS("_TtC11ZohoDeskSDK23NotificationLinkHandler")
@interface NotificationLinkHandler : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK7Product")
@interface Product : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Product (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable productCode;
@property (nonatomic, copy) NSString * _Nullable productDescription;
@property (nonatomic, copy) NSString * _Nullable productName;
@property (nonatomic, strong) Department * _Nullable department;
@end

@class TicketJsonObject;
@class TicketDetailJsonObject;
@class ThreadsJsonObject;
@class ThreadDetailJsonObject;
@class TicketForm;

/// This class provoide all apis
SWIFT_CLASS("_TtC11ZohoDeskSDK9Provoider")
@interface Provoider : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Provoider * _Nonnull sharedInstance;)
+ (Provoider * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// This method list all department for the specific department
/// \param onComplition Array of departments or error
///
- (void)getDepartmentsOnComplition:(void (^ _Nonnull)(NSArray<DepartmentJsonObject *> * _Nullable, NSError * _Nullable))onComplition;
/// This will get list of ticket for loged in user
/// \param startIndex start index of the ticket
///
/// \param limit limit
///
/// \param onCompletion Responce from server
///
- (void)getListOfTicketWithStartIndex:(NSInteger)startIndex limit:(NSInteger)limit onCompletion:(void (^ _Nonnull)(NSArray<TicketJsonObject *> * _Nullable, NSError * _Nullable))onCompletion;
/// This will Detail of the Particular Ticket ID
/// \param ticketID Id of the Ticket
///
/// \param onCompletion Responce from server.
///
- (void)getTicketWithTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(TicketDetailJsonObject * _Nullable, NSError * _Nullable))onCompletion;
/// This will get the list of Threads in particular Ticket.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     ticketId: Id of the ticket
///   </li>
///   <li>
///     onCompletion: Responce from server.
///   </li>
/// </ul>
- (void)getThreadsWithTicketId:(NSString * _Nonnull)ticketId onCompletion:(void (^ _Nonnull)(NSArray<ThreadsJsonObject *> * _Nullable, NSError * _Nullable))onCompletion;
/// This will get the Detail of the particular thread.
/// \param ticketID Id of the ticket
///
/// \param threadID ID of the Thread.
///
/// \param onCompletion Responce from server.
///
- (void)getThreadDetailWithTicketID:(NSString * _Nonnull)ticketID threadID:(NSString * _Nonnull)threadID onCompletion:(void (^ _Nonnull)(ThreadDetailJsonObject * _Nullable, NSError * _Nullable))onCompletion;
/// This method will create ticket
/// \param form ticket form object its contain user inut values
///
/// \param onCompletion created ticket detail or error.
///
- (void)createTicketWithForm:(TicketForm * _Nonnull)form onCompletion:(void (^ _Nonnull)(TicketDetailJsonObject * _Nullable, NSError * _Nullable))onCompletion;
- (UIViewController * _Nonnull)getTicketDetailControllerWithTicketID:(NSString * _Nonnull)ticketID SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK9Solutions")
@interface Solutions : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Solutions (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addAttachmentsObject:(Attachments * _Nonnull)value;
- (void)removeAttachmentsObject:(Attachments * _Nonnull)value;
- (void)addAttachments:(NSSet * _Nonnull)values;
- (void)removeAttachments:(NSSet * _Nonnull)values;
@end


@interface Solutions (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable answer;
@property (nonatomic, copy) NSString * _Nullable author;
@property (nonatomic, copy) NSString * _Nullable categoryId;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable currentUserVote;
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, copy) NSString * _Nullable dislikeCount;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable likeCount;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nullable summary;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSSet * _Nullable attachments;
@property (nonatomic, strong) Catagory * _Nullable category;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK22ThreadDetailJsonObject")
@interface ThreadDetailJsonObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull channel;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nonnull direction;
@property (nonatomic) BOOL hasAttach;
@property (nonatomic, copy) NSString * _Nonnull threadID;
@property (nonatomic) BOOL isDraft;
@property (nonatomic, copy) NSString * _Nonnull responderId;
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic, copy) NSString * _Nonnull responderName;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable attachments;
@property (nonatomic, copy) NSString * _Nonnull fromEmailId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK16ThreadJsonObject")
@interface ThreadJsonObject : NSObject
@property (nonatomic) BOOL hasAttach;
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic) BOOL isDraft;
@property (nonatomic, copy) NSString * _Nonnull channel;
@property (nonatomic, copy) NSString * _Nonnull responderName;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nonnull responderId;
@property (nonatomic, copy) NSString * _Nonnull responderPhotoURL;
@property (nonatomic, copy) NSString * _Nonnull fromEmail;
@property (nonatomic, copy) NSString * _Nonnull threadId;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull direction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK7Threads")
@interface Threads : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Threads (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addAttachmentObject:(Attachments * _Nonnull)value;
- (void)removeAttachmentObject:(Attachments * _Nonnull)value;
- (void)addAttachment:(NSSet * _Nonnull)values;
- (void)removeAttachment:(NSSet * _Nonnull)values;
@end

@class Tickets;

@interface Threads (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable fromEmail;
@property (nonatomic) BOOL hasAttach;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL isDraft;
@property (nonatomic, copy) NSString * _Nullable responderName;
@property (nonatomic, copy) NSString * _Nullable responderPhotoURL;
@property (nonatomic, copy) NSString * _Nullable responsderId;
@property (nonatomic, copy) NSString * _Nullable summary;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSDate * _Nullable createdTimeDate;
@property (nonatomic, strong) NSSet * _Nullable attachment;
@property (nonatomic, strong) Tickets * _Nullable ticket;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK17ThreadsJsonObject")
@interface ThreadsJsonObject : NSObject
@property (nonatomic) BOOL hasAttach;
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic) BOOL isDraft;
@property (nonatomic, copy) NSString * _Nonnull channel;
@property (nonatomic, copy) NSString * _Nonnull responderName;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nonnull responderId;
@property (nonatomic, copy) NSString * _Nonnull responderPhotoURL;
@property (nonatomic, copy) NSString * _Nonnull fromEmail;
@property (nonatomic, copy) NSString * _Nonnull threadId;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull direction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK13TicketComment")
@interface TicketComment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface TicketComment (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addAttachementsObject:(Attachments * _Nonnull)value;
- (void)removeAttachementsObject:(Attachments * _Nonnull)value;
- (void)addAttachements:(NSSet * _Nonnull)values;
- (void)removeAttachements:(NSSet * _Nonnull)values;
@end


@interface TicketComment (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable commentedTime;
@property (nonatomic, copy) NSString * _Nullable commenterId;
@property (nonatomic, copy) NSString * _Nullable commenterName;
@property (nonatomic, copy) NSString * _Nullable commenterphotoURL;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSDate * _Nullable modifiedTimeDate;
@property (nonatomic, strong) NSSet * _Nullable attachements;
@property (nonatomic, strong) Tickets * _Nullable ticket;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK23TicketCommentJsonObject")
@interface TicketCommentJsonObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull modifiedTime;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> * _Nullable attachments;
@property (nonatomic, copy) NSString * _Nonnull commentedTime;
@property (nonatomic, copy) NSString * _Nonnull commentId;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic, copy) NSString * _Nonnull commenterId;
@property (nonatomic, copy) NSString * _Nonnull commenterphotoURL;
@property (nonatomic, copy) NSString * _Nonnull commenterName;
@property (nonatomic, copy) NSString * _Nonnull direction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK22TicketDetailJsonObject")
@interface TicketDetailJsonObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull responseDueDate;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nonnull modifiedByUserID;
@property (nonatomic, copy) NSString * _Nonnull modifiedByUserphotoURL;
@property (nonatomic, copy) NSString * _Nonnull modifiedByUsername;
@property (nonatomic, copy) NSString * _Nonnull ticketNumber;
@property (nonatomic, copy) NSString * _Nonnull resolution;
@property (nonatomic, copy) NSString * _Nonnull creatorPhotoURL;
@property (nonatomic, copy) NSString * _Nonnull creatorName;
@property (nonatomic, copy) NSString * _Nonnull ticketId;
@property (nonatomic, copy) NSString * _Nonnull closedTime;
@property (nonatomic, copy) NSString * _Nonnull descriptionData;
@property (nonatomic, copy) NSString * _Nonnull priority;
@property (nonatomic, copy) NSString * _Nonnull assigneeId;
@property (nonatomic, copy) NSString * _Nonnull dueDate;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable customFields;
@property (nonatomic, copy) NSString * _Nonnull modifiedTime;
@property (nonatomic, copy) NSString * _Nonnull assigneephotoURL;
@property (nonatomic, copy) NSString * _Nonnull assigneeName;
@property (nonatomic, copy) NSString * _Nonnull commentCount;
@property (nonatomic, copy) NSString * _Nonnull productId;
@property (nonatomic, copy) NSString * _Nonnull category;
@property (nonatomic, copy) NSString * _Nonnull contactId;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull threadCount;
@property (nonatomic, copy) NSString * _Nonnull classification;
@property (nonatomic, copy) NSString * _Nonnull departmentId;
@property (nonatomic, copy) NSString * _Nonnull channel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK26TicketDetailViewController")
@interface TicketDetailViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end









@class QLPreviewController;
@protocol QLPreviewItem;

@interface TicketDetailViewController (SWIFT_EXTENSION(ZohoDeskSDK)) <QLPreviewControllerDataSource, QLPreviewControllerDelegate>
- (NSInteger)numberOfPreviewItemsInPreviewController:(QLPreviewController * _Nonnull)controller SWIFT_WARN_UNUSED_RESULT;
- (id <QLPreviewItem> _Nonnull)previewController:(QLPreviewController * _Nonnull)controller previewItemAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (void)previewControllerWillDismiss:(QLPreviewController * _Nonnull)controller;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK12TicketFields")
@interface TicketFields : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;

@interface TicketFields (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable allowedValues;
@property (nonatomic, copy) NSString * _Nullable decimalPlaces;
@property (nonatomic, copy) NSString * _Nullable defaultValue;
@property (nonatomic, strong) NSData * _Nullable dependencyMapping;
@property (nonatomic, copy) NSString * _Nullable displayLabel;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL isCustomField;
@property (nonatomic) BOOL isMandatory;
@property (nonatomic) int16_t maxLength;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t order;
@property (nonatomic, strong) NSData * _Nullable statusMapping;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, strong) Department * _Nullable department;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK22TicketFieldsJsonObject")
@interface TicketFieldsJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK10TicketForm")
@interface TicketForm : NSObject
@property (nonatomic, copy) NSString * _Nonnull emailID;
@property (nonatomic, copy) NSString * _Nonnull departmentID;
@property (nonatomic, copy) NSString * _Nonnull productID;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull classification;
@property (nonatomic, copy) NSString * _Nonnull priority;
@property (nonatomic, copy) NSString * _Nonnull category;
@property (nonatomic, copy) NSString * _Nonnull subCategory;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull uploads;
@property (nonatomic, copy) NSArray<CustomFields *> * _Nullable customFields;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK16TicketJsonObject")
@interface TicketJsonObject : NSObject
@property (nonatomic, copy) NSString * _Nonnull ticketNumber;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nonnull departmentId;
@property (nonatomic, copy) NSString * _Nonnull dueDate;
@property (nonatomic, copy) NSString * _Nonnull channel;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nonnull threadCount;
@property (nonatomic, copy) NSString * _Nonnull ticketId;
@property (nonatomic, copy) NSString * _Nonnull assigneeId;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, copy) NSString * _Nonnull priority;
@property (nonatomic, copy) NSString * _Nonnull commentCount;
@property (nonatomic, copy) NSString * _Nonnull closedTime;
@property (nonatomic, copy) NSDate * _Nonnull createdTimeDate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK7Tickets")
@interface Tickets : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Tickets (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addThreadsObject:(Threads * _Nonnull)value;
- (void)removeThreadsObject:(Threads * _Nonnull)value;
- (void)addThreads:(NSSet * _Nonnull)values;
- (void)removeThreads:(NSSet * _Nonnull)values;
@end


@interface Tickets (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addTicketCommentsObject:(TicketComment * _Nonnull)value;
- (void)removeTicketCommentsObject:(TicketComment * _Nonnull)value;
- (void)addTicketComments:(NSSet * _Nonnull)values;
- (void)removeTicketComments:(NSSet * _Nonnull)values;
@end


@interface Tickets (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable assigneeId;
@property (nonatomic, copy) NSString * _Nullable assigneeName;
@property (nonatomic, copy) NSString * _Nullable assigneephotoURL;
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable classification;
@property (nonatomic, copy) NSString * _Nullable closedTime;
@property (nonatomic, copy) NSString * _Nullable commentCount;
@property (nonatomic, copy) NSString * _Nullable contactId;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable createdTimeDate;
@property (nonatomic, copy) NSString * _Nullable creatorName;
@property (nonatomic, copy) NSString * _Nullable creatorPhotoURL;
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, copy) NSString * _Nullable descriptionData;
@property (nonatomic, copy) NSString * _Nullable dueDate;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable modifiedByUserID;
@property (nonatomic, copy) NSString * _Nullable modifiedByUsername;
@property (nonatomic, copy) NSString * _Nullable modifiedByUserphotoURL;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable priority;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable resolution;
@property (nonatomic, copy) NSString * _Nullable responseDueDate;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable subject;
@property (nonatomic, copy) NSString * _Nullable threadCount;
@property (nonatomic, copy) NSString * _Nullable ticketnumber;
@property (nonatomic, strong) NSDate * _Nullable createdDate;
@property (nonatomic, strong) NSSet * _Nullable threads;
@property (nonatomic, strong) NSSet * _Nullable ticketComments;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK13TopicComments")
@interface TopicComments : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface TopicComments (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addAttachmentsObject:(Attachments * _Nonnull)value;
- (void)removeAttachmentsObject:(Attachments * _Nonnull)value;
- (void)addAttachments:(NSSet * _Nonnull)values;
- (void)removeAttachments:(NSSet * _Nonnull)values;
@end


@interface TopicComments (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable creatorId;
@property (nonatomic, copy) NSString * _Nullable creatorName;
@property (nonatomic, copy) NSString * _Nullable creatorPhotoUrl;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable parentId;
@property (nonatomic, strong) NSSet * _Nullable attachments;
@property (nonatomic, strong) Topics * _Nullable topic;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK6Topics")
@interface Topics : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Topics (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addTopicCommentsObject:(TopicComments * _Nonnull)value;
- (void)removeTopicCommentsObject:(TopicComments * _Nonnull)value;
- (void)addTopicComments:(NSSet * _Nonnull)values;
- (void)removeTopicComments:(NSSet * _Nonnull)values;
@end


@interface Topics (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)addAttachmentsObject:(Attachments * _Nonnull)value;
- (void)removeAttachmentsObject:(Attachments * _Nonnull)value;
- (void)addAttachments:(NSSet * _Nonnull)values;
- (void)removeAttachments:(NSSet * _Nonnull)values;
@end


@interface Topics (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable categoryId;
@property (nonatomic, copy) NSString * _Nullable commentCount;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable creatorId;
@property (nonatomic, copy) NSString * _Nullable creatorName;
@property (nonatomic, copy) NSString * _Nullable creatorPhotoUrl;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic, copy) NSString * _Nullable latestCommenterId;
@property (nonatomic, copy) NSString * _Nullable latestCommenterName;
@property (nonatomic, copy) NSString * _Nullable latestCommentTime;
@property (nonatomic, copy) NSString * _Nullable likeCount;
@property (nonatomic, strong) NSDate * _Nullable localCreatedTime;
@property (nonatomic, copy) NSString * _Nullable permalink;
@property (nonatomic, copy) NSString * _Nullable subject;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) BOOL isDraft;
@property (nonatomic) BOOL isFollowing;
@property (nonatomic) BOOL isVoted;
@property (nonatomic, copy) NSString * _Nullable followersCount;
@property (nonatomic, strong) NSSet * _Nullable attachments;
@property (nonatomic, strong) NSSet * _Nullable topicComments;
@end
























@interface UIImageView (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)downloadImageFromUrl:(NSString * _Nullable)url cacheMinutes:(NSInteger)minutes callBack:(void (^ _Nonnull)(NSString * _Nonnull, UIImage * _Nullable))callBack;
@end


































@interface UIViewController (SWIFT_EXTENSION(ZohoDeskSDK)) <UIGestureRecognizerDelegate>
@end

@class UIGestureRecognizer;
@class UITouch;
@protocol UIViewControllerAnimatedTransitioning;

@interface UIViewController (SWIFT_EXTENSION(ZohoDeskSDK)) <UIViewControllerTransitioningDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIWindow (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, readonly, strong) UIViewController * _Nullable visibleViewControllerFromWindow;
+ (UIViewController * _Nullable)getVisibleViewControllerfromParent:(UIViewController * _Nullable)vc SWIFT_WARN_UNUSED_RESULT;
@end




SWIFT_CLASS("_TtC11ZohoDeskSDK10UserSearch")
@interface UserSearch : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserSearch (SWIFT_EXTENSION(ZohoDeskSDK))
@property (nonatomic, copy) NSString * _Nullable userKeyword;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK13VisitorObject")
@interface VisitorObject : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable email;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK28ZDBaseContollerConfiguration")
@interface ZDBaseContollerConfiguration : NSObject
@property (nonatomic) BOOL showLeftMenu;
@property (nonatomic) BOOL enableControllerTransactionAnimation;
@property (nonatomic) BOOL enableFullScreenIniPad;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK24ZDCommunityConfiguration")
@interface ZDCommunityConfiguration : ZDBaseContollerConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK25ZDHelpCenterConfiguration")
@interface ZDHelpCenterConfiguration : ZDBaseContollerConfiguration
@property (nonatomic) BOOL allowUserFeedback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK23ZDLiveChatConfiguration")
@interface ZDLiveChatConfiguration : ZDBaseContollerConfiguration
@property (nonatomic, copy) NSString * _Nonnull vistiorName;
@property (nonatomic, strong) UIColor * _Null_unspecified messageWindowColor;
@property (nonatomic, strong) UIColor * _Null_unspecified incomingMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Null_unspecified outgoingMessageBackgroundColor;
@property (nonatomic) BOOL clearPreviousChatMessages;
@property (nonatomic) BOOL showAgentPhoto;
@property (nonatomic) BOOL showRating;
@property (nonatomic) BOOL showFeedback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK21ZDPortalConfiguration")
@interface ZDPortalConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableLogMessages;)
+ (BOOL)enableLogMessages SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableLogMessages:(BOOL)newValue;
@property (nonatomic) BOOL enableChat;
@property (nonatomic) BOOL enableCommunity;
@property (nonatomic) BOOL enableHelpCenter;
@property (nonatomic) BOOL enableMyTicket;
@property (nonatomic) BOOL enableCreateTicket;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull setSDKLanguvage;)
+ (NSString * _Nonnull)setSDKLanguvage SWIFT_WARN_UNUSED_RESULT;
+ (void)setSetSDKLanguvage:(NSString * _Nonnull)newValue;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK27ZDSolutionPageConfiguration")
@interface ZDSolutionPageConfiguration : ZDBaseContollerConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11ZohoDeskSDK21ZDTicketConfiguration")
@interface ZDTicketConfiguration : ZDBaseContollerConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol ZohoDeskchatDelegate;

SWIFT_CLASS("_TtC11ZohoDeskSDK17ZohoDeskPortalSDK")
@interface ZohoDeskPortalSDK : ChatActivityHandler
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) id <ZohoDeskchatDelegate> _Nullable chatDelegate;)
+ (id <ZohoDeskchatDelegate> _Nullable)chatDelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)setChatDelegate:(id <ZohoDeskchatDelegate> _Nullable)value;
+ (void)initializeSDK:(NSString * _Nonnull)orgId appId:(NSString * _Nonnull)appId configuration:(ZDPortalConfiguration * _Nonnull)configuration;
- (void)handleWidgetActionWithIsOpen:(BOOL)isOpen;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskSDK))
@end


SWIFT_CLASS("_TtCC11ZohoDeskSDK17ZohoDeskPortalSDK22AddtionalConfiguration")
@interface AddtionalConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull LanguageCode;)
+ (NSString * _Nonnull)LanguageCode SWIFT_WARN_UNUSED_RESULT;
+ (void)setLanguageCode:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableComunity;)
+ (BOOL)enableComunity SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableComunity:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableHelpCenter;)
+ (BOOL)enableHelpCenter SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableHelpCenter:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableChat;)
+ (BOOL)enableChat SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableChat:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enablePoweredByZoho;)
+ (BOOL)enablePoweredByZoho SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnablePoweredByZoho:(BOOL)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskSDK))
+ (void)setWithJwtUserIdentifier:(NSString * _Nonnull)jwtUserIdentifier onComplition:(void (^ _Nonnull)(void))onComplition onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
+ (void)logout;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskSDK))
+ (void)enablePushNotificationWithDeviceToken:(NSString * _Nonnull)deviceToken;
+ (void)didReceiveRemoteNotificationWithUserInfo:(NSDictionary * _Nonnull)userInfo;
@end




@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskSDK))
+ (void)showHomePageWithController:(UIViewController * _Nonnull)controller withConfiguration:(ZDPortalConfiguration * _Nonnull)withConfiguration;
+ (void)showHelpCenterWithController:(UIViewController * _Nonnull)controller with:(ZDHelpCenterConfiguration * _Nonnull)configuration;
+ (void)showLiveChatWithController:(UIViewController * _Nonnull)controller with:(ZDLiveChatConfiguration * _Nonnull)configuration;
+ (void)showCommunityWithController:(UIViewController * _Nonnull)controller with:(ZDCommunityConfiguration * _Nonnull)configuration;
+ (void)ticketListWithController:(UIViewController * _Nonnull)controller with:(ZDTicketConfiguration * _Nonnull)configuration;
+ (void)addTicketWithController:(UIViewController * _Nonnull)controller with:(ZDTicketConfiguration * _Nonnull)configuration;
+ (void)showHelpPageWithController:(UIViewController * _Nonnull)controller solutionId:(NSString * _Nonnull)solutionId with:(ZDSolutionPageConfiguration * _Nonnull)configuration;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskSDK))
- (void)setVisitorWithName:(NSString * _Nonnull)name image:(UIImage * _Nullable)image;
+ (void)showLiveChat;
+ (void)setMessageWindowWithColor:(UIColor * _Nonnull)color;
+ (void)setIncomingMessageBackgroundColorWithColor:(UIColor * _Nonnull)color;
+ (void)setOutgoingMessageBackgroundColorWithColor:(UIColor * _Nonnull)color;
@end


SWIFT_PROTOCOL("_TtP11ZohoDeskSDK20ZohoDeskchatDelegate_")
@protocol ZohoDeskchatDelegate
- (void)didCloseChatWindow:(BOOL)showButton;
- (void)didShowChatWindow;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
