#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef ZDCHAT_SWIFT_H
#define ZDCHAT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZDChat",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSEntityDescription;
@class NSManagedObjectContext;
SWIFT_CLASS_NAMED("Actor")
@interface Actor : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class Messages;
@class Reaction;
@interface Actor (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable photourl;
@property (nonatomic, copy) NSString * _Nullable service;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) Messages * _Nullable message;
@property (nonatomic, strong) Reaction * _Nullable reaction;
@end

SWIFT_CLASS_NAMED("Attachement")
@interface Attachement : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class ButtonDisplay;
@class Columns;
@class FileInputDisplay;
@interface Attachement (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable downloadURL;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable index;
@property (nonatomic) BOOL isAudio;
@property (nonatomic) BOOL isDownloaded;
@property (nonatomic) BOOL isFailed;
@property (nonatomic) BOOL isPlayed;
@property (nonatomic) BOOL isUploaded;
@property (nonatomic) BOOL isUserInput;
@property (nonatomic) BOOL isVideo;
@property (nonatomic, copy) NSString * _Nullable localFilePath;
@property (nonatomic, copy) NSString * _Nullable mimeType;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) double playedProgress;
@property (nonatomic, copy) NSString * _Nullable size;
@property (nonatomic, copy) NSString * _Nullable thumpURL;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) ButtonDisplay * _Nullable button;
@property (nonatomic, strong) Columns * _Nullable layout;
@property (nonatomic, strong) Messages * _Nullable message;
@property (nonatomic, strong) FileInputDisplay * _Nullable upload;
@end

SWIFT_CLASS_NAMED("ButtonDisplay")
@interface ButtonDisplay : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class ViewProperties;
@interface ButtonDisplay (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic, copy) NSString * _Nullable displayValue;
@property (nonatomic, copy) NSString * _Nullable emoji;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable source;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, strong) Attachement * _Nullable attachment;
@property (nonatomic, strong) Columns * _Nullable column;
@property (nonatomic, strong) ViewProperties * _Nullable properties;
@end

SWIFT_CLASS_NAMED("Card")
@interface Card : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Rows;
@class NSSet;
@interface Card (SWIFT_EXTENSION(ZDChat))
- (void)addRowsObject:(Rows * _Nonnull)value;
- (void)removeRowsObject:(Rows * _Nonnull)value;
- (void)addRows:(NSSet * _Nonnull)values;
- (void)removeRows:(NSSet * _Nonnull)values;
@end

@interface Card (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic) BOOL isEnabled;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, strong) Columns * _Nullable column;
@property (nonatomic, strong) NSSet * _Nullable rows;
@end

SWIFT_CLASS_NAMED("ChatInput")
@interface ChatInput : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface ChatInput (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable accept;
@property (nonatomic, copy) NSString * _Nullable currencyType;
@property (nonatomic, copy) NSString * _Nullable defaultValue;
@property (nonatomic, copy) NSString * _Nullable displayFormat;
@property (nonatomic, copy) NSString * _Nullable max;
@property (nonatomic, copy) NSString * _Nullable min;
@property (nonatomic, copy) NSString * _Nullable size;
@property (nonatomic, copy) NSString * _Nullable step;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) Columns * _Nullable column;
@property (nonatomic, strong) Messages * _Nullable message;
@end

SWIFT_CLASS("_TtC6ZDChat9ChatUIKit")
@interface ChatUIKit : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("Columns")
@interface Columns : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class LabelDisplay;
@class SliderDisplay;
@class WebDisplay;
@interface Columns (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic) double height;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable idforView;
@property (nonatomic) int16_t index;
@property (nonatomic) BOOL isHeightCalculated;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic) double width;
@property (nonatomic, strong) Attachement * _Nullable attachements;
@property (nonatomic, strong) ButtonDisplay * _Nullable buttonDisplay;
@property (nonatomic, strong) Card * _Nullable card;
@property (nonatomic, strong) FileInputDisplay * _Nullable fileInputDisplay;
@property (nonatomic, strong) ChatInput * _Nullable input;
@property (nonatomic, strong) LabelDisplay * _Nullable labelDisplay;
@property (nonatomic, strong) Rows * _Nullable row;
@property (nonatomic, strong) SliderDisplay * _Nullable sliderDisplay;
@property (nonatomic, strong) WebDisplay * _Nullable webDisplay;
@end

SWIFT_CLASS_NAMED("Configuration")
@interface Configuration : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Configuration (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable value;
@end

SWIFT_CLASS_NAMED("ExternalConfiguration")
@interface ExternalConfiguration : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface ExternalConfiguration (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic, strong) Messages * _Nullable message;
@end

SWIFT_CLASS_NAMED("FileInputDisplay")
@interface FileInputDisplay : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface FileInputDisplay (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable accept;
@property (nonatomic, copy) NSString * _Nullable size;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) Attachement * _Nullable attachement;
@property (nonatomic, strong) Columns * _Nullable column;
@end

SWIFT_CLASS_NAMED("LabelDisplay")
@interface LabelDisplay : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface LabelDisplay (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable displayValue;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable style;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, strong) Columns * _Nullable column;
@property (nonatomic, strong) ViewProperties * _Nullable properties;
@end

SWIFT_CLASS_NAMED("Layouts")
@interface Layouts : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Layouts (SWIFT_EXTENSION(ZDChat))
- (void)addRowsObject:(Rows * _Nonnull)value;
- (void)removeRowsObject:(Rows * _Nonnull)value;
- (void)addRows:(NSSet * _Nonnull)values;
- (void)removeRows:(NSSet * _Nonnull)values;
@end

@interface Layouts (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable userInput;
@property (nonatomic, strong) Messages * _Nullable message;
@property (nonatomic, strong) NSSet * _Nullable rows;
@end

SWIFT_CLASS_NAMED("Messages")
@interface Messages : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Messages (SWIFT_EXTENSION(ZDChat))
- (void)addAttachmentsObject:(Attachement * _Nonnull)value;
- (void)removeAttachmentsObject:(Attachement * _Nonnull)value;
- (void)addAttachments:(NSSet * _Nonnull)values;
- (void)removeAttachments:(NSSet * _Nonnull)values;
@end

@class Meta;
@interface Messages (SWIFT_EXTENSION(ZDChat))
- (void)addMetaObject:(Meta * _Nonnull)value;
- (void)removeMetaObject:(Meta * _Nonnull)value;
- (void)addMeta:(NSSet * _Nonnull)values;
- (void)removeMeta:(NSSet * _Nonnull)values;
@end

@interface Messages (SWIFT_EXTENSION(ZDChat))
- (void)addReactionObject:(Reaction * _Nonnull)value;
- (void)removeReactionObject:(Reaction * _Nonnull)value;
- (void)addReaction:(NSSet * _Nonnull)values;
- (void)removeReaction:(NSSet * _Nonnull)values;
@end

@class NSDate;
@class PreviewMeta;
@class Sessions;
@interface Messages (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable actionfailed;
@property (nonatomic, copy) NSString * _Nullable chatInput;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) double index;
@property (nonatomic) BOOL isEnd;
@property (nonatomic) BOOL isHeightCalculated;
@property (nonatomic) BOOL isIncoming;
@property (nonatomic) int16_t isMultiSelection;
@property (nonatomic) BOOL isSkipped;
@property (nonatomic) BOOL isSupportEnabled;
@property (nonatomic) BOOL isUserInput;
@property (nonatomic, copy) NSString * _Nullable localID;
@property (nonatomic) double messageHeight;
@property (nonatomic, copy) NSString * _Nullable messagepattern;
@property (nonatomic, copy) NSString * _Nullable messagePostion;
@property (nonatomic, copy) NSString * _Nullable messageStatus;
@property (nonatomic) double messageWidth;
@property (nonatomic, copy) NSDate * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nullable questionId;
@property (nonatomic, copy) NSString * _Nullable refreshId;
@property (nonatomic, copy) NSString * _Nullable summary;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable uniqueId;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, copy) NSString * _Nullable vote;
@property (nonatomic, strong) Actor * _Nullable actor;
@property (nonatomic, strong) NSSet * _Nullable attachments;
@property (nonatomic, strong) ExternalConfiguration * _Nullable externalConfiguration;
@property (nonatomic, strong) ChatInput * _Nullable input;
@property (nonatomic, strong) Layouts * _Nullable layouts;
@property (nonatomic, strong) NSSet * _Nullable meta;
@property (nonatomic, strong) PreviewMeta * _Nullable previewMeta;
@property (nonatomic, strong) NSSet * _Nullable reaction;
@property (nonatomic, strong) Messages * _Nullable repliedMessage;
@property (nonatomic, strong) Sessions * _Nullable sessions;
@property (nonatomic, strong) Messages * _Nullable userInput;
@end

SWIFT_CLASS_NAMED("Meta")
@interface Meta : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Meta (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable displayValue;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, strong) Messages * _Nullable message;
@end

SWIFT_CLASS_NAMED("PreviewMeta")
@interface PreviewMeta : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface PreviewMeta (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) Messages * _Nullable message;
@end

SWIFT_CLASS_NAMED("Reaction")
@interface Reaction : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Reaction (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSDate * _Nullable reactedTime;
@property (nonatomic, strong) Actor * _Nullable actor;
@property (nonatomic, strong) Messages * _Nullable message;
@end

SWIFT_CLASS_NAMED("Rows")
@interface Rows : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSIndexSet;
@class NSOrderedSet;
@interface Rows (SWIFT_EXTENSION(ZDChat))
- (void)insertObject:(Columns * _Nonnull)value inColoumnsAtIndex:(NSInteger)idx;
- (void)removeObjectFromColoumnsAtIndex:(NSInteger)idx;
- (void)insertColoumns:(NSArray<Columns *> * _Nonnull)values atIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)removeColoumnsAtIndexes:(NSIndexSet * _Nonnull)indexes;
- (void)replaceObjectInColoumnsAtIndex:(NSInteger)idx withObject:(Columns * _Nonnull)value;
- (void)replaceColoumnsAtIndexes:(NSIndexSet * _Nonnull)indexes withColoumns:(NSArray<Columns *> * _Nonnull)values;
- (void)addColoumnsObject:(Columns * _Nonnull)value;
- (void)removeColoumnsObject:(Columns * _Nonnull)value;
- (void)addColoumns:(NSOrderedSet * _Nonnull)values;
- (void)removeColoumns:(NSOrderedSet * _Nonnull)values;
@end

@interface Rows (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable action;
@property (nonatomic, copy) NSString * _Nullable arrangement;
@property (nonatomic, copy) NSString * _Nullable displayValue;
@property (nonatomic) double height;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int16_t index;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic) double width;
@property (nonatomic, strong) Card * _Nullable card;
@property (nonatomic, strong) NSOrderedSet * _Nullable coloumns;
@property (nonatomic, strong) Layouts * _Nullable layouts;
@end

SWIFT_CLASS_NAMED("Sessions")
@interface Sessions : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Sessions (SWIFT_EXTENSION(ZDChat))
- (void)addMessagesObject:(Messages * _Nonnull)value;
- (void)removeMessagesObject:(Messages * _Nonnull)value;
- (void)addMessages:(NSSet * _Nonnull)values;
- (void)removeMessages:(NSSet * _Nonnull)values;
@end

@interface Sessions (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable service;
@property (nonatomic, strong) NSSet * _Nullable messages;
@end

SWIFT_CLASS_NAMED("SliderDisplay")
@interface SliderDisplay : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface SliderDisplay (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable defaultValue;
@property (nonatomic, copy) NSString * _Nullable maxDisplayValue;
@property (nonatomic, copy) NSString * _Nullable maximum;
@property (nonatomic, copy) NSString * _Nullable minDisplayValue;
@property (nonatomic, copy) NSString * _Nullable minimum;
@property (nonatomic, copy) NSString * _Nullable step;
@property (nonatomic, copy) NSString * _Nullable userInput;
@property (nonatomic, strong) Columns * _Nullable column;
@end

SWIFT_CLASS_NAMED("TextMessage")
@interface TextMessage : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface TextMessage (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable messageContent;
@property (nonatomic, strong) Messages * _Nullable message;
@end

SWIFT_CLASS_NAMED("ViewProperties")
@interface ViewProperties : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface ViewProperties (SWIFT_EXTENSION(ZDChat))
@property (nonatomic) double height;
@property (nonatomic) BOOL isSelfSizing;
@property (nonatomic) double width;
@property (nonatomic, strong) ButtonDisplay * _Nullable buttonDisplay;
@property (nonatomic, strong) LabelDisplay * _Nullable labelDisplay;
@property (nonatomic, strong) WebDisplay * _Nullable webview;
@end

SWIFT_CLASS_NAMED("WebDisplay")
@interface WebDisplay : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface WebDisplay (SWIFT_EXTENSION(ZDChat))
@property (nonatomic, copy) NSString * _Nullable html;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, strong) Columns * _Nullable column;
@property (nonatomic, strong) ViewProperties * _Nullable properties;
@end

typedef SWIFT_ENUM(NSInteger, ZDChatAction, open) {
  ZDChatActionSkip = 0,
  ZDChatActionReinitate = 1,
  ZDChatActionBottransfer = 2,
  ZDChatActionInvokearticle = 3,
  ZDChatActionRate = 4,
  ZDChatActionResend = 5,
  ZDChatActionInvokechat = 6,
  ZDChatActionEnd = 7,
  ZDChatActionInvokeTicket = 8,
  ZDChatActionSend_temp = 9,
  ZDChatActionAttachmentLocal = 10,
  ZDChatActionTransferToAgent = 11,
  ZDChatActionMsgToAgent = 12,
  ZDChatActionFlowInvocation = 13,
  ZDChatActionLanguageSelection = 14,
  ZDChatActionDeleteChat = 15,
  ZDChatActionRetainAndRestart = 16,
  ZDChatActionBm_reload = 17,
  ZDChatActionBm_endChat = 18,
};

enum ZDChatScreenPresentationStyle : NSInteger;
SWIFT_PROTOCOL("_TtP6ZDChat26ZDChatScreenConfigurations_")
@protocol ZDChatScreenConfigurations
@optional
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly) enum ZDChatScreenPresentationStyle screenPresentationStyle;
@end

typedef SWIFT_ENUM(NSInteger, ZDChatScreenPresentationStyle, open) {
  ZDChatScreenPresentationStylePush = 0,
  ZDChatScreenPresentationStylePresent = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
