#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZohoDeskPortalSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK20AttachmentJsonObject")
@interface AttachmentJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC17ZohoDeskPortalSDK20DepartmentJsonObject")
@interface DepartmentJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC17ZohoDeskPortalSDK17ProductJsonObject")
@interface ProductJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK22TicketDetailJsonObject")
@interface TicketDetailJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK22TicketFieldsJsonObject")
@interface TicketFieldsJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end













@class UIViewController;

@interface UINavigationController (SWIFT_EXTENSION(ZohoDeskPortalSDK))
@property (nonatomic, readonly, strong) UIViewController * _Nullable childViewControllerForStatusBarStyle;
@end



































enum ZDAnalyticsTrackingType : NSInteger;
enum ZDPortalControllers : NSInteger;
enum ZDPortalUIAction : NSInteger;

SWIFT_CLASS("_TtC17ZohoDeskPortalSDK11ZDAnalytics")
@interface ZDAnalytics : NSObject
- (enum ZDAnalyticsTrackingType)getTrackingType SWIFT_WARN_UNUSED_RESULT;
- (enum ZDPortalControllers)getEventScreen SWIFT_WARN_UNUSED_RESULT;
- (enum ZDPortalControllers)getEventSource SWIFT_WARN_UNUSED_RESULT;
- (enum ZDPortalUIAction)getEventAction SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getlabelValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZDAnalyticsTrackingType, closed) {
  ZDAnalyticsTrackingTypeEvent = 0,
  ZDAnalyticsTrackingTypeLaunch = 1,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK28ZDBaseContollerConfiguration")
@interface ZDBaseContollerConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK19ZDCommunityCategory")
@interface ZDCommunityCategory : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK24ZDCommunityConfiguration")
@interface ZDCommunityConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZDCommunityConfiguration * _Nonnull configure;)
+ (ZDCommunityConfiguration * _Nonnull)configure SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfigure:(ZDCommunityConfiguration * _Nonnull)value;
@property (nonatomic) BOOL isTopicEditAllowed;
@property (nonatomic) BOOL isTopicDeleteAllowed;
@property (nonatomic) BOOL isReplyAllowed;
@property (nonatomic) BOOL isReplyEditAllowed;
@property (nonatomic) BOOL isReplyDeleteAllowed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK16ZDCommunityTopic")
@interface ZDCommunityTopic : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZDVisibleTicketField;
@class ZDCustomizedTicketForm;

SWIFT_CLASS("_TtC17ZohoDeskPortalSDK27ZDCreateTicketConfiguration")
@interface ZDCreateTicketConfiguration : NSObject
+ (void)setFieldsListTobeShownWithFields:(NSArray<ZDVisibleTicketField *> * _Nonnull)fields;
+ (void)preFillTicketFieldsForForms:(NSArray<ZDCustomizedTicketForm *> * _Nonnull)forms;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK14ZDCustomFields")
@interface ZDCustomFields : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK12ZDCustomFont")
@interface ZDCustomFont : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull fontFamilyName;
@property (nonatomic, copy) NSString * _Nonnull regularFontName;
@property (nonatomic, copy) NSString * _Nonnull lightFontName;
@property (nonatomic, copy) NSString * _Nonnull mediumFontName;
@property (nonatomic, copy) NSString * _Nonnull boldFontName;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK13ZDCustomTheme")
@interface ZDCustomTheme : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull tintColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryTextColor;
@property (nonatomic, strong) UIColor * _Nonnull secondryTextColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull secondryBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull cellSeporatorColor;
@property (nonatomic, strong) UIColor * _Nonnull headerColor;
@property (nonatomic, strong) UIColor * _Nonnull accentColor;
@property (nonatomic, strong) UIColor * _Nonnull mandatoryTextColor;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK23ZDCustomizedTicketField")
@interface ZDCustomizedTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK22ZDCustomizedTicketForm")
@interface ZDCustomizedTicketForm : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZDDataCenter, closed) {
  ZDDataCenterUS = 0,
  ZDDataCenterCN = 1,
  ZDDataCenterEU = 2,
  ZDDataCenterIN = 3,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK25ZDHelpCenterConfiguration")
@interface ZDHelpCenterConfiguration : ZDBaseContollerConfiguration
@property (nonatomic) BOOL allowUserFeedback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK23ZDLiveChatConfiguration")
@interface ZDLiveChatConfiguration : ZDBaseContollerConfiguration
@property (nonatomic, copy) NSString * _Nonnull vistiorName;
@property (nonatomic, strong) UIColor * _Null_unspecified messageWindowColor;
@property (nonatomic, strong) UIColor * _Null_unspecified incomingMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Null_unspecified outgoingMessageBackgroundColor;
@property (nonatomic) BOOL clearPreviousChatMessages;
@property (nonatomic) BOOL showAgentPhoto;
@property (nonatomic) BOOL showRating;
@property (nonatomic) BOOL showFeedback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDNavigation, closed) {
  ZDNavigationPush = 0,
  ZDNavigationPresent = 1,
};

typedef SWIFT_ENUM(NSInteger, ZDNavigationBackButtonStyle, closed) {
  ZDNavigationBackButtonStyleText = 0,
  ZDNavigationBackButtonStyleIcon = 1,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK17ZDNavigationTheme")
@interface ZDNavigationTheme : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull navigationBarColor;)
+ (UIColor * _Nonnull)navigationBarColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setNavigationBarColor:(UIColor * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull titleColor;)
+ (UIColor * _Nonnull)titleColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setTitleColor:(UIColor * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull barButtonTextColor;)
+ (UIColor * _Nonnull)barButtonTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setBarButtonTextColor:(UIColor * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL translucent;)
+ (BOOL)translucent SWIFT_WARN_UNUSED_RESULT;
+ (void)setTranslucent:(BOOL)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) UIStatusBarStyle statusBarApperance;)
+ (UIStatusBarStyle)statusBarApperance SWIFT_WARN_UNUSED_RESULT;
+ (void)setStatusBarApperance:(UIStatusBarStyle)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum ZDNavigationBackButtonStyle backButtonStyle;)
+ (enum ZDNavigationBackButtonStyle)backButtonStyle SWIFT_WARN_UNUSED_RESULT;
+ (void)setBackButtonStyle:(enum ZDNavigationBackButtonStyle)newValue;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK21ZDPortalConfiguration")
@interface ZDPortalConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (void)setGuestUserWithEmail:(NSString * _Nonnull)email displayName:(NSString * _Nullable)displayName phoneNumber:(NSString * _Nullable)phoneNumber;
+ (void)disableZDKnowledgeBaseCategoriesWithCategoryIds:(NSArray<NSString *> * _Nonnull)CategoryIds;
+ (void)processConfigurationWithConfig:(ZDPortalConfiguration * _Nonnull)config;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableLogMessages;)
+ (BOOL)enableLogMessages SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableLogMessages:(BOOL)newValue;
@property (nonatomic) BOOL enableCommunity;
@property (nonatomic) BOOL enableHelpCenter;
@property (nonatomic) BOOL enableMyTicket;
@property (nonatomic) BOOL enableCreateTicket;
@property (nonatomic) BOOL showLeftMenu;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull setSDKLanguage;)
+ (NSString * _Nonnull)setSDKLanguage SWIFT_WARN_UNUSED_RESULT;
+ (void)setSetSDKLanguage:(NSString * _Nonnull)newValue;
@end

typedef SWIFT_ENUM(NSInteger, ZDPortalControllers, closed) {
  ZDPortalControllersDashBoard = 0,
  ZDPortalControllersKBCategoryList = 1,
  ZDPortalControllersKBChildCategoryList = 2,
  ZDPortalControllersKBSearchList = 3,
  ZDPortalControllersKBArticleList = 4,
  ZDPortalControllersKBArticleDetail = 5,
  ZDPortalControllersKBRelatedArticles = 6,
  ZDPortalControllersFeedBack = 7,
  ZDPortalControllersKBDeeplinking = 8,
  ZDPortalControllersCommunityCatagories = 9,
  ZDPortalControllersCommunityTopicsList = 10,
  ZDPortalControllersCommunityTopicDetail = 11,
  ZDPortalControllersCommunityCreateTopic = 12,
  ZDPortalControllersCommunityTopicReply = 13,
  ZDPortalControllersDirectlyOpenFromApplication = 14,
  ZDPortalControllersNil = 15,
};

typedef SWIFT_ENUM(NSInteger, ZDPortalUIAction, closed) {
  ZDPortalUIActionDashBoardKBClicked = 0,
  ZDPortalUIActionDashBoardCommunityClicked = 1,
  ZDPortalUIActionDashBoardMyTicketClicked = 2,
  ZDPortalUIActionDashBoardCreateTicketClicked = 3,
  ZDPortalUIActionKBCategoryClicked = 4,
  ZDPortalUIActionKBChildCategoryClicked = 5,
  ZDPortalUIActionKBArticleClicked = 6,
  ZDPortalUIActionKBRelatedArticleClicked = 7,
  ZDPortalUIActionKBSearchedArticleClicked = 8,
  ZDPortalUIActionKBSearchedCategoryClicked = 9,
  ZDPortalUIActionKBArticleUpVoted = 10,
  ZDPortalUIActionKBArticleDownVoted = 11,
  ZDPortalUIActionKBArticleFeedBackSent = 12,
  ZDPortalUIActionKBArticleFeedBackSkip = 13,
  ZDPortalUIActionCommunityCategoryClicked = 14,
  ZDPortalUIActionCommunityCategoryFollow = 15,
  ZDPortalUIActionCommunityCategoryUnFollow = 16,
  ZDPortalUIActionCommunityTopicClicked = 17,
  ZDPortalUIActionCommunityForumClicked = 18,
  ZDPortalUIActionCommunityTopicTypeFilter = 19,
  ZDPortalUIActionCommunityTopicFollow = 20,
  ZDPortalUIActionCommunityTopicUnFollow = 21,
  ZDPortalUIActionCommunityTopicLiked = 22,
  ZDPortalUIActionCommunityTopicCommentAction = 23,
  ZDPortalUIActionCommunityTopicCommentSent = 24,
  ZDPortalUIActionCommunityTopicCommentCreateCancel = 25,
  ZDPortalUIActionCommunityTopicDeleted = 26,
  ZDPortalUIActionCommunityTopicEdited = 27,
  ZDPortalUIActionCommunityTopicCreated = 28,
  ZDPortalUIActionCommunityTopicCreateCancel = 29,
  ZDPortalUIActionCommunityTopicSavedAsDraft = 30,
  ZDPortalUIActionNil = 31,
};

@class ZDTicketForm;

/// This class provoide all apis
SWIFT_CLASS("_TtC17ZohoDeskPortalSDK11ZDProvoider")
@interface ZDProvoider : NSObject
/// This method list all department for the specific department
/// \param onComplition Array of departments or error
///
- (void)getDepartmentsOnCompletion:(void (^ _Nonnull)(NSArray<DepartmentJsonObject *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method list all Product for the specific department
/// \param onComplition Array of Product or error
///
- (void)getProductsFor:(NSString * _Nonnull)departmentId from:(NSInteger)from limit:(NSInteger)limit onCompletion:(void (^ _Nonnull)(NSArray<ProductJsonObject *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method to Get dynamic Ticket Form
/// \param onCompletion Array of Ticket Fields or error
///
- (void)getTicketForm:(NSString * _Nonnull)departmentId onCompletion:(void (^ _Nonnull)(NSArray<TicketFieldsJsonObject *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// Upload Ticket Attachement
/// \param onCompletion Responce from server
///
- (void)uploadTicketAttachment:(NSString * _Nonnull)filePath onCompletion:(void (^ _Nonnull)(AttachmentJsonObject * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method will create ticket
/// \param form ticket form object its contain user inut values
///
/// \param onCompletion created ticket detail or error.
///
- (void)createTicketWithForm:(ZDTicketForm * _Nonnull)form onCompletion:(void (^ _Nonnull)(TicketDetailJsonObject * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method list all department for the specific department
/// \param onComplition Array of departments or error
///
- (void)getZDCommunityCategoriesOnCompletion:(void (^ _Nonnull)(NSArray<ZDCommunityCategory *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (void)getZDMostPopularCommunityTopicsForCategory:(NSString * _Nullable)categoryId filterType:(NSString * _Nonnull)filterType from:(NSInteger)from limit:(NSInteger)limit includeCount:(BOOL)includeCount :(void (^ _Nonnull)(NSArray<ZDCommunityTopic *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (void)getZDMostDiscussedCommunityTopicsForCategory:(NSString * _Nullable)categoryId filterType:(NSString * _Nonnull)filterType from:(NSInteger)from limit:(NSInteger)limit includeCount:(BOOL)includeCount :(void (^ _Nonnull)(NSArray<ZDCommunityTopic *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (void)getZDCommunityCategoryByPermalink:(NSString * _Nonnull)permalink :(void (^ _Nonnull)(ZDCommunityCategory * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// Method used for update user information.
/// @param userInfo - Need to send the key value pair you have to update.
- (void)UpdateUserInformationWithUserInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo :(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK27ZDSolutionPageConfiguration")
@interface ZDSolutionPageConfiguration : ZDBaseContollerConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZDThemeType : NSInteger;

SWIFT_CLASS("_TtC17ZohoDeskPortalSDK7ZDTheme")
@interface ZDTheme : NSObject
+ (void)applyThemeWithTheme:(enum ZDThemeType)theme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDThemeType, closed) {
  ZDThemeTypeWhite = 0,
  ZDThemeTypeDark = 1,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK21ZDTicketConfiguration")
@interface ZDTicketConfiguration : ZDBaseContollerConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK12ZDTicketForm")
@interface ZDTicketForm : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDTopicType, closed) {
  ZDTopicTypeIdea = 0,
  ZDTopicTypeQuestion = 1,
  ZDTopicTypeProblem = 2,
  ZDTopicTypeAnnouncement = 3,
  ZDTopicTypeAllTypes = 4,
};

typedef SWIFT_ENUM(NSInteger, ZDViewController, closed) {
  ZDViewControllerDashBoard = 0,
  ZDViewControllerKBCategoryList = 1,
  ZDViewControllerKBArticleDetail = 2,
  ZDViewControllerCommunityCatagories = 3,
  ZDViewControllerCommunityTopicDetail = 4,
  ZDViewControllerMyTicketList = 5,
  ZDViewControllerCreateTicket = 6,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK20ZDVisibleTicketField")
@interface ZDVisibleTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP17ZohoDeskPortalSDK22ZohoDeskPortalDelegate_")
@protocol ZohoDeskPortalDelegate
- (void)didCloseChatWindow:(BOOL)showButton;
- (void)didShowChatWindow;
- (void)handleBadgeCountWithCount:(NSInteger)count;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK17ZohoDeskPortalSDK")
@interface ZohoDeskPortalSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
@end


SWIFT_CLASS("_TtCC17ZohoDeskPortalSDK17ZohoDeskPortalSDK24ZDAddtionalConfiguration")
@interface ZDAddtionalConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
- (void)setVisitorWithName:(NSString * _Nonnull)name image:(UIImage * _Nullable)image;
@end






@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
+ (void)clearAllLocalData;
+ (void)logout;
+ (void)logoutOnComplition:(void (^ _Nonnull)(void))onComplition onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isZDUserSignedIn;)
+ (BOOL)isZDUserSignedIn SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isZDSDKMigratedTo1_0;)
+ (BOOL)isZDSDKMigratedTo1_0 SWIFT_WARN_UNUSED_RESULT;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
+ (void)showHomePageWithController:(UIViewController * _Nonnull)controller withConfiguration:(ZDPortalConfiguration * _Nonnull)withConfiguration;
+ (void)showHomePageWithController:(UIViewController * _Nonnull)controller navigationType:(enum ZDNavigation)navigationType withConfiguration:(ZDPortalConfiguration * _Nonnull)withConfiguration;
+ (void)showHelpCenterWithController:(UIViewController * _Nonnull)controller;
+ (void)showArticleListForCategoryId:(NSString * _Nonnull)categoryId controller:(UIViewController * _Nonnull)controller with:(ZDHelpCenterConfiguration * _Nonnull)configuration;
+ (void)showLiveChatWithController:(UIViewController * _Nonnull)controller;
+ (void)showCommunityWithController:(UIViewController * _Nonnull)controller;
+ (void)ticketListWithController:(UIViewController * _Nonnull)controller;
+ (void)addTicketWithController:(UIViewController * _Nonnull)controller;
+ (void)addTicketWithController:(UIViewController * _Nonnull)controller onCompletion:(void (^ _Nonnull)(TicketDetailJsonObject * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
+ (void)showHelpPageForArticleId:(NSString * _Nonnull)articleId controller:(UIViewController * _Nonnull)controller with:(ZDSolutionPageConfiguration * _Nonnull)configuration;
+ (void)showHelpPageForArticleUrl:(NSURL * _Nonnull)articleLink controller:(UIViewController * _Nonnull)controller with:(ZDSolutionPageConfiguration * _Nonnull)configuration;
+ (void)ZDAnalyticsTrackerOnCompletion:(void (^ _Nonnull)(ZDAnalytics * _Nullable))onCompletion;
+ (void)dismissControllerOnCompletion:(void (^ _Nonnull)(enum ZDViewController))onCompletion;
+ (void)showTopicDetailForTopicId:(NSString * _Nonnull)topicId controller:(UIViewController * _Nonnull)controller;
+ (void)showCatgoryByPermalinkForPermaLink:(NSString * _Nonnull)permaLink controller:(UIViewController * _Nonnull)controller;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZohoDeskPortalSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK20AttachmentJsonObject")
@interface AttachmentJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC17ZohoDeskPortalSDK20DepartmentJsonObject")
@interface DepartmentJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end








SWIFT_CLASS("_TtC17ZohoDeskPortalSDK17ProductJsonObject")
@interface ProductJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK22TicketDetailJsonObject")
@interface TicketDetailJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK22TicketFieldsJsonObject")
@interface TicketFieldsJsonObject : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end













@class UIViewController;

@interface UINavigationController (SWIFT_EXTENSION(ZohoDeskPortalSDK))
@property (nonatomic, readonly, strong) UIViewController * _Nullable childViewControllerForStatusBarStyle;
@end



































enum ZDAnalyticsTrackingType : NSInteger;
enum ZDPortalControllers : NSInteger;
enum ZDPortalUIAction : NSInteger;

SWIFT_CLASS("_TtC17ZohoDeskPortalSDK11ZDAnalytics")
@interface ZDAnalytics : NSObject
- (enum ZDAnalyticsTrackingType)getTrackingType SWIFT_WARN_UNUSED_RESULT;
- (enum ZDPortalControllers)getEventScreen SWIFT_WARN_UNUSED_RESULT;
- (enum ZDPortalControllers)getEventSource SWIFT_WARN_UNUSED_RESULT;
- (enum ZDPortalUIAction)getEventAction SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getlabelValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZDAnalyticsTrackingType, closed) {
  ZDAnalyticsTrackingTypeEvent = 0,
  ZDAnalyticsTrackingTypeLaunch = 1,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK28ZDBaseContollerConfiguration")
@interface ZDBaseContollerConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK19ZDCommunityCategory")
@interface ZDCommunityCategory : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK24ZDCommunityConfiguration")
@interface ZDCommunityConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZDCommunityConfiguration * _Nonnull configure;)
+ (ZDCommunityConfiguration * _Nonnull)configure SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfigure:(ZDCommunityConfiguration * _Nonnull)value;
@property (nonatomic) BOOL isTopicEditAllowed;
@property (nonatomic) BOOL isTopicDeleteAllowed;
@property (nonatomic) BOOL isReplyAllowed;
@property (nonatomic) BOOL isReplyEditAllowed;
@property (nonatomic) BOOL isReplyDeleteAllowed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK16ZDCommunityTopic")
@interface ZDCommunityTopic : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZDVisibleTicketField;
@class ZDCustomizedTicketForm;

SWIFT_CLASS("_TtC17ZohoDeskPortalSDK27ZDCreateTicketConfiguration")
@interface ZDCreateTicketConfiguration : NSObject
+ (void)setFieldsListTobeShownWithFields:(NSArray<ZDVisibleTicketField *> * _Nonnull)fields;
+ (void)preFillTicketFieldsForForms:(NSArray<ZDCustomizedTicketForm *> * _Nonnull)forms;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK14ZDCustomFields")
@interface ZDCustomFields : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK12ZDCustomFont")
@interface ZDCustomFont : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull fontFamilyName;
@property (nonatomic, copy) NSString * _Nonnull regularFontName;
@property (nonatomic, copy) NSString * _Nonnull lightFontName;
@property (nonatomic, copy) NSString * _Nonnull mediumFontName;
@property (nonatomic, copy) NSString * _Nonnull boldFontName;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK13ZDCustomTheme")
@interface ZDCustomTheme : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull tintColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryTextColor;
@property (nonatomic, strong) UIColor * _Nonnull secondryTextColor;
@property (nonatomic, strong) UIColor * _Nonnull primaryBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull secondryBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull cellSeporatorColor;
@property (nonatomic, strong) UIColor * _Nonnull headerColor;
@property (nonatomic, strong) UIColor * _Nonnull accentColor;
@property (nonatomic, strong) UIColor * _Nonnull mandatoryTextColor;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK23ZDCustomizedTicketField")
@interface ZDCustomizedTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK22ZDCustomizedTicketForm")
@interface ZDCustomizedTicketForm : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZDDataCenter, closed) {
  ZDDataCenterUS = 0,
  ZDDataCenterCN = 1,
  ZDDataCenterEU = 2,
  ZDDataCenterIN = 3,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK25ZDHelpCenterConfiguration")
@interface ZDHelpCenterConfiguration : ZDBaseContollerConfiguration
@property (nonatomic) BOOL allowUserFeedback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK23ZDLiveChatConfiguration")
@interface ZDLiveChatConfiguration : ZDBaseContollerConfiguration
@property (nonatomic, copy) NSString * _Nonnull vistiorName;
@property (nonatomic, strong) UIColor * _Null_unspecified messageWindowColor;
@property (nonatomic, strong) UIColor * _Null_unspecified incomingMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Null_unspecified outgoingMessageBackgroundColor;
@property (nonatomic) BOOL clearPreviousChatMessages;
@property (nonatomic) BOOL showAgentPhoto;
@property (nonatomic) BOOL showRating;
@property (nonatomic) BOOL showFeedback;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDNavigation, closed) {
  ZDNavigationPush = 0,
  ZDNavigationPresent = 1,
};

typedef SWIFT_ENUM(NSInteger, ZDNavigationBackButtonStyle, closed) {
  ZDNavigationBackButtonStyleText = 0,
  ZDNavigationBackButtonStyleIcon = 1,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK17ZDNavigationTheme")
@interface ZDNavigationTheme : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull navigationBarColor;)
+ (UIColor * _Nonnull)navigationBarColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setNavigationBarColor:(UIColor * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull titleColor;)
+ (UIColor * _Nonnull)titleColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setTitleColor:(UIColor * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) UIColor * _Nonnull barButtonTextColor;)
+ (UIColor * _Nonnull)barButtonTextColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setBarButtonTextColor:(UIColor * _Nonnull)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL translucent;)
+ (BOOL)translucent SWIFT_WARN_UNUSED_RESULT;
+ (void)setTranslucent:(BOOL)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) UIStatusBarStyle statusBarApperance;)
+ (UIStatusBarStyle)statusBarApperance SWIFT_WARN_UNUSED_RESULT;
+ (void)setStatusBarApperance:(UIStatusBarStyle)newValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum ZDNavigationBackButtonStyle backButtonStyle;)
+ (enum ZDNavigationBackButtonStyle)backButtonStyle SWIFT_WARN_UNUSED_RESULT;
+ (void)setBackButtonStyle:(enum ZDNavigationBackButtonStyle)newValue;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK21ZDPortalConfiguration")
@interface ZDPortalConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (void)setGuestUserWithEmail:(NSString * _Nonnull)email displayName:(NSString * _Nullable)displayName phoneNumber:(NSString * _Nullable)phoneNumber;
+ (void)disableZDKnowledgeBaseCategoriesWithCategoryIds:(NSArray<NSString *> * _Nonnull)CategoryIds;
+ (void)processConfigurationWithConfig:(ZDPortalConfiguration * _Nonnull)config;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL enableLogMessages;)
+ (BOOL)enableLogMessages SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableLogMessages:(BOOL)newValue;
@property (nonatomic) BOOL enableCommunity;
@property (nonatomic) BOOL enableHelpCenter;
@property (nonatomic) BOOL enableMyTicket;
@property (nonatomic) BOOL enableCreateTicket;
@property (nonatomic) BOOL showLeftMenu;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull setSDKLanguage;)
+ (NSString * _Nonnull)setSDKLanguage SWIFT_WARN_UNUSED_RESULT;
+ (void)setSetSDKLanguage:(NSString * _Nonnull)newValue;
@end

typedef SWIFT_ENUM(NSInteger, ZDPortalControllers, closed) {
  ZDPortalControllersDashBoard = 0,
  ZDPortalControllersKBCategoryList = 1,
  ZDPortalControllersKBChildCategoryList = 2,
  ZDPortalControllersKBSearchList = 3,
  ZDPortalControllersKBArticleList = 4,
  ZDPortalControllersKBArticleDetail = 5,
  ZDPortalControllersKBRelatedArticles = 6,
  ZDPortalControllersFeedBack = 7,
  ZDPortalControllersKBDeeplinking = 8,
  ZDPortalControllersCommunityCatagories = 9,
  ZDPortalControllersCommunityTopicsList = 10,
  ZDPortalControllersCommunityTopicDetail = 11,
  ZDPortalControllersCommunityCreateTopic = 12,
  ZDPortalControllersCommunityTopicReply = 13,
  ZDPortalControllersDirectlyOpenFromApplication = 14,
  ZDPortalControllersNil = 15,
};

typedef SWIFT_ENUM(NSInteger, ZDPortalUIAction, closed) {
  ZDPortalUIActionDashBoardKBClicked = 0,
  ZDPortalUIActionDashBoardCommunityClicked = 1,
  ZDPortalUIActionDashBoardMyTicketClicked = 2,
  ZDPortalUIActionDashBoardCreateTicketClicked = 3,
  ZDPortalUIActionKBCategoryClicked = 4,
  ZDPortalUIActionKBChildCategoryClicked = 5,
  ZDPortalUIActionKBArticleClicked = 6,
  ZDPortalUIActionKBRelatedArticleClicked = 7,
  ZDPortalUIActionKBSearchedArticleClicked = 8,
  ZDPortalUIActionKBSearchedCategoryClicked = 9,
  ZDPortalUIActionKBArticleUpVoted = 10,
  ZDPortalUIActionKBArticleDownVoted = 11,
  ZDPortalUIActionKBArticleFeedBackSent = 12,
  ZDPortalUIActionKBArticleFeedBackSkip = 13,
  ZDPortalUIActionCommunityCategoryClicked = 14,
  ZDPortalUIActionCommunityCategoryFollow = 15,
  ZDPortalUIActionCommunityCategoryUnFollow = 16,
  ZDPortalUIActionCommunityTopicClicked = 17,
  ZDPortalUIActionCommunityForumClicked = 18,
  ZDPortalUIActionCommunityTopicTypeFilter = 19,
  ZDPortalUIActionCommunityTopicFollow = 20,
  ZDPortalUIActionCommunityTopicUnFollow = 21,
  ZDPortalUIActionCommunityTopicLiked = 22,
  ZDPortalUIActionCommunityTopicCommentAction = 23,
  ZDPortalUIActionCommunityTopicCommentSent = 24,
  ZDPortalUIActionCommunityTopicCommentCreateCancel = 25,
  ZDPortalUIActionCommunityTopicDeleted = 26,
  ZDPortalUIActionCommunityTopicEdited = 27,
  ZDPortalUIActionCommunityTopicCreated = 28,
  ZDPortalUIActionCommunityTopicCreateCancel = 29,
  ZDPortalUIActionCommunityTopicSavedAsDraft = 30,
  ZDPortalUIActionNil = 31,
};

@class ZDTicketForm;

/// This class provoide all apis
SWIFT_CLASS("_TtC17ZohoDeskPortalSDK11ZDProvoider")
@interface ZDProvoider : NSObject
/// This method list all department for the specific department
/// \param onComplition Array of departments or error
///
- (void)getDepartmentsOnCompletion:(void (^ _Nonnull)(NSArray<DepartmentJsonObject *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method list all Product for the specific department
/// \param onComplition Array of Product or error
///
- (void)getProductsFor:(NSString * _Nonnull)departmentId from:(NSInteger)from limit:(NSInteger)limit onCompletion:(void (^ _Nonnull)(NSArray<ProductJsonObject *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method to Get dynamic Ticket Form
/// \param onCompletion Array of Ticket Fields or error
///
- (void)getTicketForm:(NSString * _Nonnull)departmentId onCompletion:(void (^ _Nonnull)(NSArray<TicketFieldsJsonObject *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// Upload Ticket Attachement
/// \param onCompletion Responce from server
///
- (void)uploadTicketAttachment:(NSString * _Nonnull)filePath onCompletion:(void (^ _Nonnull)(AttachmentJsonObject * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method will create ticket
/// \param form ticket form object its contain user inut values
///
/// \param onCompletion created ticket detail or error.
///
- (void)createTicketWithForm:(ZDTicketForm * _Nonnull)form onCompletion:(void (^ _Nonnull)(TicketDetailJsonObject * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// This method list all department for the specific department
/// \param onComplition Array of departments or error
///
- (void)getZDCommunityCategoriesOnCompletion:(void (^ _Nonnull)(NSArray<ZDCommunityCategory *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (void)getZDMostPopularCommunityTopicsForCategory:(NSString * _Nullable)categoryId filterType:(NSString * _Nonnull)filterType from:(NSInteger)from limit:(NSInteger)limit includeCount:(BOOL)includeCount :(void (^ _Nonnull)(NSArray<ZDCommunityTopic *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (void)getZDMostDiscussedCommunityTopicsForCategory:(NSString * _Nullable)categoryId filterType:(NSString * _Nonnull)filterType from:(NSInteger)from limit:(NSInteger)limit includeCount:(BOOL)includeCount :(void (^ _Nonnull)(NSArray<ZDCommunityTopic *> * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (void)getZDCommunityCategoryByPermalink:(NSString * _Nonnull)permalink :(void (^ _Nonnull)(ZDCommunityCategory * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
/// Method used for update user information.
/// @param userInfo - Need to send the key value pair you have to update.
- (void)UpdateUserInformationWithUserInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo :(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK27ZDSolutionPageConfiguration")
@interface ZDSolutionPageConfiguration : ZDBaseContollerConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZDThemeType : NSInteger;

SWIFT_CLASS("_TtC17ZohoDeskPortalSDK7ZDTheme")
@interface ZDTheme : NSObject
+ (void)applyThemeWithTheme:(enum ZDThemeType)theme;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDThemeType, closed) {
  ZDThemeTypeWhite = 0,
  ZDThemeTypeDark = 1,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK21ZDTicketConfiguration")
@interface ZDTicketConfiguration : ZDBaseContollerConfiguration
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK12ZDTicketForm")
@interface ZDTicketForm : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZDTopicType, closed) {
  ZDTopicTypeIdea = 0,
  ZDTopicTypeQuestion = 1,
  ZDTopicTypeProblem = 2,
  ZDTopicTypeAnnouncement = 3,
  ZDTopicTypeAllTypes = 4,
};

typedef SWIFT_ENUM(NSInteger, ZDViewController, closed) {
  ZDViewControllerDashBoard = 0,
  ZDViewControllerKBCategoryList = 1,
  ZDViewControllerKBArticleDetail = 2,
  ZDViewControllerCommunityCatagories = 3,
  ZDViewControllerCommunityTopicDetail = 4,
  ZDViewControllerMyTicketList = 5,
  ZDViewControllerCreateTicket = 6,
};


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK20ZDVisibleTicketField")
@interface ZDVisibleTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP17ZohoDeskPortalSDK22ZohoDeskPortalDelegate_")
@protocol ZohoDeskPortalDelegate
- (void)didCloseChatWindow:(BOOL)showButton;
- (void)didShowChatWindow;
- (void)handleBadgeCountWithCount:(NSInteger)count;
@end


SWIFT_CLASS("_TtC17ZohoDeskPortalSDK17ZohoDeskPortalSDK")
@interface ZohoDeskPortalSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
@end


SWIFT_CLASS("_TtCC17ZohoDeskPortalSDK17ZohoDeskPortalSDK24ZDAddtionalConfiguration")
@interface ZDAddtionalConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
- (void)setVisitorWithName:(NSString * _Nonnull)name image:(UIImage * _Nullable)image;
@end






@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
+ (void)clearAllLocalData;
+ (void)logout;
+ (void)logoutOnComplition:(void (^ _Nonnull)(void))onComplition onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isZDUserSignedIn;)
+ (BOOL)isZDUserSignedIn SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isZDSDKMigratedTo1_0;)
+ (BOOL)isZDSDKMigratedTo1_0 SWIFT_WARN_UNUSED_RESULT;
@end


@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalSDK))
+ (void)showHomePageWithController:(UIViewController * _Nonnull)controller withConfiguration:(ZDPortalConfiguration * _Nonnull)withConfiguration;
+ (void)showHomePageWithController:(UIViewController * _Nonnull)controller navigationType:(enum ZDNavigation)navigationType withConfiguration:(ZDPortalConfiguration * _Nonnull)withConfiguration;
+ (void)showHelpCenterWithController:(UIViewController * _Nonnull)controller;
+ (void)showArticleListForCategoryId:(NSString * _Nonnull)categoryId controller:(UIViewController * _Nonnull)controller with:(ZDHelpCenterConfiguration * _Nonnull)configuration;
+ (void)showLiveChatWithController:(UIViewController * _Nonnull)controller;
+ (void)showCommunityWithController:(UIViewController * _Nonnull)controller;
+ (void)ticketListWithController:(UIViewController * _Nonnull)controller;
+ (void)addTicketWithController:(UIViewController * _Nonnull)controller;
+ (void)addTicketWithController:(UIViewController * _Nonnull)controller onCompletion:(void (^ _Nonnull)(TicketDetailJsonObject * _Nullable))onCompletion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
+ (void)showHelpPageForArticleId:(NSString * _Nonnull)articleId controller:(UIViewController * _Nonnull)controller with:(ZDSolutionPageConfiguration * _Nonnull)configuration;
+ (void)showHelpPageForArticleUrl:(NSURL * _Nonnull)articleLink controller:(UIViewController * _Nonnull)controller with:(ZDSolutionPageConfiguration * _Nonnull)configuration;
+ (void)ZDAnalyticsTrackerOnCompletion:(void (^ _Nonnull)(ZDAnalytics * _Nullable))onCompletion;
+ (void)dismissControllerOnCompletion:(void (^ _Nonnull)(enum ZDViewController))onCompletion;
+ (void)showTopicDetailForTopicId:(NSString * _Nonnull)topicId controller:(UIViewController * _Nonnull)controller;
+ (void)showCatgoryByPermalinkForPermaLink:(NSString * _Nonnull)permaLink controller:(UIViewController * _Nonnull)controller;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
