#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef MOBILISTENCORE_SWIFT_H
#define MOBILISTENCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MobilistenCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_PROTOCOL("_TtP14MobilistenCore8SIQError_")
@protocol SIQError
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@end

SWIFT_CLASS("_TtC14MobilistenCore15APIErrorWrapper")
@interface APIErrorWrapper : NSObject <SIQError>
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APNSMode, open) {
  APNSModeSandbox = 0,
  APNSModeProduction = 1,
};

enum ChatErrorCode : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore9ChatError")
@interface ChatError : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithError:(enum ChatErrorCode)error customMessage:(NSString * _Nonnull)customMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ChatErrorCode, open) {
  ChatErrorCodeCreationFailed = 0,
  ChatErrorCodeFormSyncFailed = 1,
  ChatErrorCodeTriggerTimedOut = 2,
  ChatErrorCodeMessagesSyncFailed = 3,
  ChatErrorCodeTriggerFailed = 4,
  ChatErrorCodeSocketConnectionFailed = 5,
};

/// ChatStatus
/// \code
/// case open
/// case waiting
/// case closed
/// case missed
///
/// \endcode
typedef SWIFT_ENUM(NSInteger, ChatStatus, open) {
/// Combined list of chats whose status include: connected, waiting, proactive, triggered
  ChatStatusOpen = 0,
/// Chats which are tiggered by a bot or an intelligent trigger
  ChatStatusTriggered = 1,
/// Chats which proactively initiated by an operator.
  ChatStatusProactive = 2,
/// Chats which are connected to an operator or bot
  ChatStatusConnected = 3,
/// Chats which are awaiting response from an operator
  ChatStatusWaiting = 4,
/// Chats which have gone missed
  ChatStatusMissed = 5,
/// Chats which have been closed
  ChatStatusClosed = 6,
/// Chats which have been closed or gone missed
  ChatStatusEnded = 7,
/// All chats
  ChatStatusAll = 8,
};

enum ResourceErrorCode : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore13ResourceError")
@interface ResourceError : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithError:(enum ResourceErrorCode)error customMessage:(NSString * _Nonnull)customMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ResourceErrorCode, open) {
  ResourceErrorCodeArticleCatergorySyncFailed = 0,
  ResourceErrorCodeArticleSyncFailed = 1,
  ResourceErrorCodeArticleSearchFailed = 2,
};

@class SIQDepartment;
@class UIImage;
SWIFT_CLASS("_TtC14MobilistenCore11SIQCallInfo")
@interface SIQCallInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable additionalInfo;
@property (nonatomic, copy) NSArray<SIQDepartment *> * _Nonnull departments;
@property (nonatomic, strong) UIImage * _Nullable displayImage;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SIQCommunicationMode, open) {
  SIQCommunicationModeChat = 0,
  SIQCommunicationModeCall = 1,
  SIQCommunicationModeChatAndCall = 2,
  SIQCommunicationModeNone = 3,
};

SWIFT_CLASS("_TtC14MobilistenCore13SIQDepartment")
@interface SIQDepartment : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL available;
@property (nonatomic) enum SIQCommunicationMode mode;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name available:(BOOL)available mode:(enum SIQCommunicationMode)mode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithId:(NSString * _Nullable)id name:(NSString * _Nullable)name mode:(enum SIQCommunicationMode)mode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SIQVisitorMessage;
SWIFT_CLASS("_TtC14MobilistenCore14SIQVisitorChat")
@interface SIQVisitorChat : NSObject
@property (nonatomic, copy) NSString * _Nullable attenderEmail;
@property (nonatomic, copy) NSString * _Nullable attenderID;
@property (nonatomic, copy) NSString * _Nullable attenderName;
@property (nonatomic, copy) NSString * _Nullable departmentName;
@property (nonatomic, copy) NSString * _Nullable feedback;
@property (nonatomic) BOOL isBotAttender;
@property (nonatomic, strong) SIQVisitorMessage * _Nonnull lastMessage;
@property (nonatomic, copy) NSString * _Nullable question;
@property (nonatomic, copy) NSString * _Nullable rating;
@property (nonatomic, copy) NSString * _Nullable referenceID;
@property (nonatomic) enum ChatStatus status;
@property (nonatomic) NSInteger unreadCount;
@property (nonatomic) NSInteger queuePosition;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14MobilistenCore14SIQVisitorFile")
@interface SIQVisitorFile : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger size;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nullable comment;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name size:(NSInteger)size contentType:(NSString * _Nonnull)contentType comment:(NSString * _Nullable)comment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;
SWIFT_CLASS("_TtC14MobilistenCore17SIQVisitorMessage")
@interface SIQVisitorMessage : NSObject
@property (nonatomic, copy) NSDate * _Nullable time;
@property (nonatomic, copy) NSString * _Nullable sender;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) BOOL isRead;
@property (nonatomic) BOOL isEdited;
@property (nonatomic) BOOL isDeleted;
@property (nonatomic, strong) SIQVisitorFile * _Nullable file;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SalesIQMedia;
SWIFT_CLASS("_TtC14MobilistenCore19SalesIQConversation")
@interface SalesIQConversation : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable customConversationId;
@property (nonatomic, copy) NSString * _Nullable question;
@property (nonatomic, copy) NSString * _Nullable attenderId;
@property (nonatomic, copy) NSString * _Nullable attenderName;
@property (nonatomic, copy) NSString * _Nullable attenderEmail;
@property (nonatomic, copy) NSString * _Nullable departmentName;
@property (nonatomic, copy) NSString * _Nullable feedback;
@property (nonatomic, copy) NSString * _Nullable rating;
@property (nonatomic) NSInteger queuePosition;
@property (nonatomic, strong) SalesIQMedia * _Nullable media;
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum SalesIQCallConversationStatus : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore11SalesIQCall")
@interface SalesIQCall : SalesIQConversation
@property (nonatomic) enum SalesIQCallConversationStatus status;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SalesIQCallConversationStatus, open) {
  SalesIQCallConversationStatusNone = 0,
  SalesIQCallConversationStatusWaiting = 1,
  SalesIQCallConversationStatusConnected = 2,
  SalesIQCallConversationStatusMissed = 3,
  SalesIQCallConversationStatusClosed = 4,
};

@class SalesIQLastMessage;
SWIFT_CLASS("_TtC14MobilistenCore11SalesIQChat")
@interface SalesIQChat : SalesIQConversation
@property (nonatomic) BOOL isBotAttender;
@property (nonatomic) NSInteger unreadCount;
@property (nonatomic, strong) SalesIQLastMessage * _Nullable lastMessage;
@property (nonatomic) enum ChatStatus status;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14MobilistenCore11SalesIQFile")
@interface SalesIQFile : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable contentType;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) NSInteger size;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SalesIQSenderDetail;
enum SalesIQMessageStatus : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore18SalesIQLastMessage")
@interface SalesIQLastMessage : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) SalesIQSenderDetail * _Nullable sender;
@property (nonatomic, copy) NSDate * _Nullable time;
@property (nonatomic) BOOL isRead;
@property (nonatomic) BOOL sentByUser;
@property (nonatomic) BOOL isEdited;
@property (nonatomic) BOOL isDeleted;
@property (nonatomic, strong) SalesIQFile * _Nullable file;
@property (nonatomic) enum SalesIQMessageStatus status;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum UserType : NSInteger;
enum SalesIQMediaStatus : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore12SalesIQMedia")
@interface SalesIQMedia : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic) enum UserType initiatedBy;
@property (nonatomic, copy) NSString * _Nullable pickupTime;
@property (nonatomic, copy) NSString * _Nullable connectedTime;
@property (nonatomic) enum SalesIQMediaStatus status;
@property (nonatomic) enum UserType endedBy;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable createdTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SalesIQMediaStatus, open) {
  SalesIQMediaStatusNone = 0,
  SalesIQMediaStatusEnded = 1,
  SalesIQMediaStatusRejected = 2,
  SalesIQMediaStatusMissed = 3,
  SalesIQMediaStatusCancelled = 4,
  SalesIQMediaStatusConnected = 5,
  SalesIQMediaStatusInvited = 6,
  SalesIQMediaStatusInitiated = 7,
  SalesIQMediaStatusAccepted = 8,
};

typedef SWIFT_ENUM(NSInteger, SalesIQMessageStatus, open) {
  SalesIQMessageStatusSending = 0,
  SalesIQMessageStatusUploading = 1,
  SalesIQMessageStatusSent = 2,
  SalesIQMessageStatusFailed = 3,
};

SWIFT_CLASS("_TtC14MobilistenCore19SalesIQSenderDetail")
@interface SalesIQSenderDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, UserType, open) {
  UserTypeNone = 0,
  UserTypeUser = 1,
  UserTypeAgent = 2,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef MOBILISTENCORE_SWIFT_H
#define MOBILISTENCORE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MobilistenCore",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_PROTOCOL("_TtP14MobilistenCore8SIQError_")
@protocol SIQError
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@end

SWIFT_CLASS("_TtC14MobilistenCore15APIErrorWrapper")
@interface APIErrorWrapper : NSObject <SIQError>
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APNSMode, open) {
  APNSModeSandbox = 0,
  APNSModeProduction = 1,
};

enum ChatErrorCode : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore9ChatError")
@interface ChatError : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithError:(enum ChatErrorCode)error customMessage:(NSString * _Nonnull)customMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ChatErrorCode, open) {
  ChatErrorCodeCreationFailed = 0,
  ChatErrorCodeFormSyncFailed = 1,
  ChatErrorCodeTriggerTimedOut = 2,
  ChatErrorCodeMessagesSyncFailed = 3,
  ChatErrorCodeTriggerFailed = 4,
  ChatErrorCodeSocketConnectionFailed = 5,
};

/// ChatStatus
/// \code
/// case open
/// case waiting
/// case closed
/// case missed
///
/// \endcode
typedef SWIFT_ENUM(NSInteger, ChatStatus, open) {
/// Combined list of chats whose status include: connected, waiting, proactive, triggered
  ChatStatusOpen = 0,
/// Chats which are tiggered by a bot or an intelligent trigger
  ChatStatusTriggered = 1,
/// Chats which proactively initiated by an operator.
  ChatStatusProactive = 2,
/// Chats which are connected to an operator or bot
  ChatStatusConnected = 3,
/// Chats which are awaiting response from an operator
  ChatStatusWaiting = 4,
/// Chats which have gone missed
  ChatStatusMissed = 5,
/// Chats which have been closed
  ChatStatusClosed = 6,
/// Chats which have been closed or gone missed
  ChatStatusEnded = 7,
/// All chats
  ChatStatusAll = 8,
};

enum ResourceErrorCode : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore13ResourceError")
@interface ResourceError : NSObject
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithError:(enum ResourceErrorCode)error customMessage:(NSString * _Nonnull)customMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ResourceErrorCode, open) {
  ResourceErrorCodeArticleCatergorySyncFailed = 0,
  ResourceErrorCodeArticleSyncFailed = 1,
  ResourceErrorCodeArticleSearchFailed = 2,
};

@class SIQDepartment;
@class UIImage;
SWIFT_CLASS("_TtC14MobilistenCore11SIQCallInfo")
@interface SIQCallInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable additionalInfo;
@property (nonatomic, copy) NSArray<SIQDepartment *> * _Nonnull departments;
@property (nonatomic, strong) UIImage * _Nullable displayImage;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, SIQCommunicationMode, open) {
  SIQCommunicationModeChat = 0,
  SIQCommunicationModeCall = 1,
  SIQCommunicationModeChatAndCall = 2,
  SIQCommunicationModeNone = 3,
};

SWIFT_CLASS("_TtC14MobilistenCore13SIQDepartment")
@interface SIQDepartment : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL available;
@property (nonatomic) enum SIQCommunicationMode mode;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id name:(NSString * _Nonnull)name available:(BOOL)available mode:(enum SIQCommunicationMode)mode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithId:(NSString * _Nullable)id name:(NSString * _Nullable)name mode:(enum SIQCommunicationMode)mode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SIQVisitorMessage;
SWIFT_CLASS("_TtC14MobilistenCore14SIQVisitorChat")
@interface SIQVisitorChat : NSObject
@property (nonatomic, copy) NSString * _Nullable attenderEmail;
@property (nonatomic, copy) NSString * _Nullable attenderID;
@property (nonatomic, copy) NSString * _Nullable attenderName;
@property (nonatomic, copy) NSString * _Nullable departmentName;
@property (nonatomic, copy) NSString * _Nullable feedback;
@property (nonatomic) BOOL isBotAttender;
@property (nonatomic, strong) SIQVisitorMessage * _Nonnull lastMessage;
@property (nonatomic, copy) NSString * _Nullable question;
@property (nonatomic, copy) NSString * _Nullable rating;
@property (nonatomic, copy) NSString * _Nullable referenceID;
@property (nonatomic) enum ChatStatus status;
@property (nonatomic) NSInteger unreadCount;
@property (nonatomic) NSInteger queuePosition;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14MobilistenCore14SIQVisitorFile")
@interface SIQVisitorFile : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger size;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nullable comment;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name size:(NSInteger)size contentType:(NSString * _Nonnull)contentType comment:(NSString * _Nullable)comment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;
SWIFT_CLASS("_TtC14MobilistenCore17SIQVisitorMessage")
@interface SIQVisitorMessage : NSObject
@property (nonatomic, copy) NSDate * _Nullable time;
@property (nonatomic, copy) NSString * _Nullable sender;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) BOOL isRead;
@property (nonatomic) BOOL isEdited;
@property (nonatomic) BOOL isDeleted;
@property (nonatomic, strong) SIQVisitorFile * _Nullable file;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SalesIQMedia;
SWIFT_CLASS("_TtC14MobilistenCore19SalesIQConversation")
@interface SalesIQConversation : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable customConversationId;
@property (nonatomic, copy) NSString * _Nullable question;
@property (nonatomic, copy) NSString * _Nullable attenderId;
@property (nonatomic, copy) NSString * _Nullable attenderName;
@property (nonatomic, copy) NSString * _Nullable attenderEmail;
@property (nonatomic, copy) NSString * _Nullable departmentName;
@property (nonatomic, copy) NSString * _Nullable feedback;
@property (nonatomic, copy) NSString * _Nullable rating;
@property (nonatomic) NSInteger queuePosition;
@property (nonatomic, strong) SalesIQMedia * _Nullable media;
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum SalesIQCallConversationStatus : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore11SalesIQCall")
@interface SalesIQCall : SalesIQConversation
@property (nonatomic) enum SalesIQCallConversationStatus status;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SalesIQCallConversationStatus, open) {
  SalesIQCallConversationStatusNone = 0,
  SalesIQCallConversationStatusWaiting = 1,
  SalesIQCallConversationStatusConnected = 2,
  SalesIQCallConversationStatusMissed = 3,
  SalesIQCallConversationStatusClosed = 4,
};

@class SalesIQLastMessage;
SWIFT_CLASS("_TtC14MobilistenCore11SalesIQChat")
@interface SalesIQChat : SalesIQConversation
@property (nonatomic) BOOL isBotAttender;
@property (nonatomic) NSInteger unreadCount;
@property (nonatomic, strong) SalesIQLastMessage * _Nullable lastMessage;
@property (nonatomic) enum ChatStatus status;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC14MobilistenCore11SalesIQFile")
@interface SalesIQFile : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable contentType;
@property (nonatomic, copy) NSString * _Nullable comment;
@property (nonatomic) NSInteger size;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SalesIQSenderDetail;
enum SalesIQMessageStatus : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore18SalesIQLastMessage")
@interface SalesIQLastMessage : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) SalesIQSenderDetail * _Nullable sender;
@property (nonatomic, copy) NSDate * _Nullable time;
@property (nonatomic) BOOL isRead;
@property (nonatomic) BOOL sentByUser;
@property (nonatomic) BOOL isEdited;
@property (nonatomic) BOOL isDeleted;
@property (nonatomic, strong) SalesIQFile * _Nullable file;
@property (nonatomic) enum SalesIQMessageStatus status;
- (nonnull instancetype)initWithDictionary:(NSDictionary<NSString *, id> * _Nonnull)dictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum UserType : NSInteger;
enum SalesIQMediaStatus : NSInteger;
SWIFT_CLASS("_TtC14MobilistenCore12SalesIQMedia")
@interface SalesIQMedia : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic) enum UserType initiatedBy;
@property (nonatomic, copy) NSString * _Nullable pickupTime;
@property (nonatomic, copy) NSString * _Nullable connectedTime;
@property (nonatomic) enum SalesIQMediaStatus status;
@property (nonatomic) enum UserType endedBy;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable createdTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SalesIQMediaStatus, open) {
  SalesIQMediaStatusNone = 0,
  SalesIQMediaStatusEnded = 1,
  SalesIQMediaStatusRejected = 2,
  SalesIQMediaStatusMissed = 3,
  SalesIQMediaStatusCancelled = 4,
  SalesIQMediaStatusConnected = 5,
  SalesIQMediaStatusInvited = 6,
  SalesIQMediaStatusInitiated = 7,
  SalesIQMediaStatusAccepted = 8,
};

typedef SWIFT_ENUM(NSInteger, SalesIQMessageStatus, open) {
  SalesIQMessageStatusSending = 0,
  SalesIQMessageStatusUploading = 1,
  SalesIQMessageStatusSent = 2,
  SalesIQMessageStatusFailed = 3,
};

SWIFT_CLASS("_TtC14MobilistenCore19SalesIQSenderDetail")
@interface SalesIQSenderDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, UserType, open) {
  UserTypeNone = 0,
  UserTypeUser = 1,
  UserTypeAgent = 2,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
