#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
#ifndef ZOHODESKPORTALTICKET_SWIFT_H
#define ZOHODESKPORTALTICKET_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import ZohoDeskPortalConfiguration;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZohoDeskPortalTicket",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS("_TtC20ZohoDeskPortalTicket10Attachment")
@interface Attachment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class TicketComment;
@class TicketThread;

@interface Attachment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable filePath;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSDate * _Nullable modifiedTimeDate;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t order;
@property (nonatomic, copy) NSString * _Nullable size;
@property (nonatomic, strong) TicketComment * _Nullable ticketComment;
@property (nonatomic, strong) TicketThread * _Nullable ticketThread;
@end



@class NSCoder;

SWIFT_CLASS("_TtC20ZohoDeskPortalTicket23DPInteractionHeaderView")
@interface DPInteractionHeaderView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setColors;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket6Ticket")
@interface Ticket : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;

@interface Ticket (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addCommentObject:(TicketComment * _Nonnull)value;
- (void)removeCommentObject:(TicketComment * _Nonnull)value;
- (void)addComment:(NSSet * _Nonnull)values;
- (void)removeComment:(NSSet * _Nonnull)values;
@end


@interface Ticket (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addThreadsObject:(TicketThread * _Nonnull)value;
- (void)removeThreadsObject:(TicketThread * _Nonnull)value;
- (void)addThreads:(NSSet * _Nonnull)values;
- (void)removeThreads:(NSSet * _Nonnull)values;
@end


@interface Ticket (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable assigneeId;
@property (nonatomic, copy) NSString * _Nullable assigneeName;
@property (nonatomic, copy) NSString * _Nullable assigneephotoURL;
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable classification;
@property (nonatomic, copy) NSString * _Nullable closedTime;
@property (nonatomic, copy) NSString * _Nullable commentCount;
@property (nonatomic, copy) NSString * _Nullable contactId;
@property (nonatomic, copy) NSDate * _Nullable createdDate;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable createdTimeDate;
@property (nonatomic, copy) NSString * _Nullable creatorName;
@property (nonatomic, copy) NSString * _Nullable creatorPhotoURL;
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, copy) NSString * _Nullable dueDate;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable modifiedByUserID;
@property (nonatomic, copy) NSString * _Nullable modifiedByUsername;
@property (nonatomic, copy) NSString * _Nullable modifiedByUserphotoURL;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic) int16_t order;
@property (nonatomic, copy) NSString * _Nullable priority;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable resolution;
@property (nonatomic, copy) NSString * _Nullable responseDueDate;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable subject;
@property (nonatomic, copy) NSString * _Nullable threadCount;
@property (nonatomic, copy) NSString * _Nullable ticketnumber;
@property (nonatomic, strong) NSSet * _Nullable comment;
@property (nonatomic, strong) NSSet * _Nullable threads;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket13TicketComment")
@interface TicketComment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface TicketComment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addAttachmentObject:(Attachment * _Nonnull)value;
- (void)removeAttachmentObject:(Attachment * _Nonnull)value;
- (void)addAttachment:(NSSet * _Nonnull)values;
- (void)removeAttachment:(NSSet * _Nonnull)values;
@end


@interface TicketComment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable commentedTime;
@property (nonatomic, copy) NSString * _Nullable commenterId;
@property (nonatomic, copy) NSString * _Nullable commenterName;
@property (nonatomic, copy) NSString * _Nullable commenterphotoURL;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSDate * _Nullable modifiedTimeDate;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSSet * _Nullable attachment;
@property (nonatomic, strong) Ticket * _Nullable ticket;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket12TicketThread")
@interface TicketThread : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface TicketThread (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addAttachmentObject:(Attachment * _Nonnull)value;
- (void)removeAttachmentObject:(Attachment * _Nonnull)value;
- (void)addAttachment:(NSSet * _Nonnull)values;
- (void)removeAttachment:(NSSet * _Nonnull)values;
@end


@interface TicketThread (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSDate * _Nullable createdTimeDate;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable fromEmail;
@property (nonatomic) BOOL hasAttach;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL isDraft;
@property (nonatomic, copy) NSString * _Nullable responderName;
@property (nonatomic, copy) NSString * _Nullable responderPhotoURL;
@property (nonatomic, copy) NSString * _Nullable responsderId;
@property (nonatomic, copy) NSString * _Nullable summary;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSSet * _Nullable attachment;
@property (nonatomic, strong) Ticket * _Nullable ticket;
@end





SWIFT_CLASS("_TtC20ZohoDeskPortalTicket23ZDCustomizedTicketField")
@interface ZDCustomizedTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket22ZDCustomizedTicketForm")
@interface ZDCustomizedTicketForm : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ZDPDepartment")
@interface ZDPDepartment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZDPDepartment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable deptDescription;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable nameInCustomerPortal;
@property (nonatomic) int16_t order;
@property (nonatomic, copy) NSString * _Nullable photoURL;
@end



SWIFT_CLASS("_TtC20ZohoDeskPortalTicket22ZDPTicketConfiguration")
@interface ZDPTicketConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZDPTicketConfiguration * _Nonnull configure;)
+ (ZDPTicketConfiguration * _Nonnull)configure SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfigure:(ZDPTicketConfiguration * _Nonnull)value;
@property (nonatomic) BOOL isReplyAllowed;
@property (nonatomic) BOOL isCommentAllowed;
@property (nonatomic) BOOL isTicketUpdateAllowed;
@property (nonatomic) BOOL isCommentEditAllowed;
@property (nonatomic) BOOL isCommentDeleteAllowed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ZDPTicketField")
@interface ZDPTicketField : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ZDPTicketField (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, strong) NSObject * _Nullable allowedValues;
@property (nonatomic, strong) NSObject * _Nullable allowedValuesServer;
@property (nonatomic, copy) NSString * _Nullable apiName;
@property (nonatomic, copy) NSString * _Nullable captchaURL;
@property (nonatomic) int16_t decimals;
@property (nonatomic, copy) NSString * _Nullable defaultValue;
@property (nonatomic, copy) NSString * _Nullable departmentID;
@property (nonatomic, strong) NSObject * _Nullable dependency;
@property (nonatomic, copy) NSString * _Nullable displayLabel;
@property (nonatomic, copy) NSString * _Nullable fieldName;
@property (nonatomic) int16_t fieldOrder;
@property (nonatomic, copy) NSString * _Nullable i18NLabel;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable initialValue;
@property (nonatomic, copy) NSString * _Nullable initialValueByClient;
@property (nonatomic) BOOL isCustomField;
@property (nonatomic) BOOL isMandatory;
@property (nonatomic) BOOL isMandatoryForLocal;
@property (nonatomic) BOOL isReadOnly;
@property (nonatomic) BOOL isReadOnlyByClient;
@property (nonatomic) BOOL isValueChanged;
@property (nonatomic) BOOL isVisible;
@property (nonatomic) BOOL isVisibleByClient;
@property (nonatomic) int32_t maxLength;
@property (nonatomic, copy) NSDate * _Nullable modifiedDate;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t precison;
@property (nonatomic, strong) NSObject * _Nullable restoreOnReplyValues;
@property (nonatomic, copy) NSString * _Nullable roundingOption;
@property (nonatomic, copy) NSString * _Nullable sectionName;
@property (nonatomic) int16_t sectionOrder;
@property (nonatomic) BOOL showField;
@property (nonatomic) BOOL showSection;
@property (nonatomic, copy) NSString * _Nullable sortBy;
@property (nonatomic, strong) NSObject * _Nullable statusMapping;
@property (nonatomic, copy) NSString * _Nullable toolTip;
@property (nonatomic, copy) NSString * _Nullable toolTipType;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable uploadAttachment;
@property (nonatomic, copy) NSString * _Nullable userInput;
@property (nonatomic, copy) NSString * _Nullable validationError;
@end

@class ZDPTicket;
@class UIViewController;
@class ZDVisibleTicketField;

SWIFT_CLASS("_TtC20ZohoDeskPortalTicket20ZDPortalSubmitTicket")
@interface ZDPortalSubmitTicket : NSObject
+ (void)showAddTicketFormWithTitle:(NSString * _Nullable)title navigationMode:(enum ZDPNavigationMode)navigationMode completion:(void (^ _Nonnull)(ZDPTicket * _Nonnull))completion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
+ (void)showWithTitle:(NSString * _Nullable)title navigationMode:(enum ZDPNavigationMode)navigationMode;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIViewController * _Nonnull viewController;)
+ (UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
+ (void)setFieldsListTobeShownWithFields:(NSArray<ZDVisibleTicketField *> * _Nonnull)fields;
+ (void)preFillTicketFieldsForForms:(NSArray<ZDCustomizedTicketForm *> * _Nonnull)forms;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket14ZDPortalTicket")
@interface ZDPortalTicket : NSObject
+ (void)showWithTitle:(NSString * _Nullable)title navigationMode:(enum ZDPNavigationMode)navigationMode;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIViewController * _Nonnull viewController;)
+ (UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket20ZDVisibleTicketField")
@interface ZDVisibleTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
#ifndef ZOHODESKPORTALTICKET_SWIFT_H
#define ZOHODESKPORTALTICKET_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import ZohoDeskPortalConfiguration;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZohoDeskPortalTicket",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS("_TtC20ZohoDeskPortalTicket10Attachment")
@interface Attachment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class TicketComment;
@class TicketThread;

@interface Attachment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable filePath;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSDate * _Nullable modifiedTimeDate;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t order;
@property (nonatomic, copy) NSString * _Nullable size;
@property (nonatomic, strong) TicketComment * _Nullable ticketComment;
@property (nonatomic, strong) TicketThread * _Nullable ticketThread;
@end



@class NSCoder;

SWIFT_CLASS("_TtC20ZohoDeskPortalTicket23DPInteractionHeaderView")
@interface DPInteractionHeaderView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)setColors;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket6Ticket")
@interface Ticket : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;

@interface Ticket (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addCommentObject:(TicketComment * _Nonnull)value;
- (void)removeCommentObject:(TicketComment * _Nonnull)value;
- (void)addComment:(NSSet * _Nonnull)values;
- (void)removeComment:(NSSet * _Nonnull)values;
@end


@interface Ticket (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addThreadsObject:(TicketThread * _Nonnull)value;
- (void)removeThreadsObject:(TicketThread * _Nonnull)value;
- (void)addThreads:(NSSet * _Nonnull)values;
- (void)removeThreads:(NSSet * _Nonnull)values;
@end


@interface Ticket (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable assigneeId;
@property (nonatomic, copy) NSString * _Nullable assigneeName;
@property (nonatomic, copy) NSString * _Nullable assigneephotoURL;
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable classification;
@property (nonatomic, copy) NSString * _Nullable closedTime;
@property (nonatomic, copy) NSString * _Nullable commentCount;
@property (nonatomic, copy) NSString * _Nullable contactId;
@property (nonatomic, copy) NSDate * _Nullable createdDate;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable createdTimeDate;
@property (nonatomic, copy) NSString * _Nullable creatorName;
@property (nonatomic, copy) NSString * _Nullable creatorPhotoURL;
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, copy) NSString * _Nullable dueDate;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable modifiedByUserID;
@property (nonatomic, copy) NSString * _Nullable modifiedByUsername;
@property (nonatomic, copy) NSString * _Nullable modifiedByUserphotoURL;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic) int16_t order;
@property (nonatomic, copy) NSString * _Nullable priority;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable resolution;
@property (nonatomic, copy) NSString * _Nullable responseDueDate;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable subject;
@property (nonatomic, copy) NSString * _Nullable threadCount;
@property (nonatomic, copy) NSString * _Nullable ticketnumber;
@property (nonatomic, strong) NSSet * _Nullable comment;
@property (nonatomic, strong) NSSet * _Nullable threads;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket13TicketComment")
@interface TicketComment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface TicketComment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addAttachmentObject:(Attachment * _Nonnull)value;
- (void)removeAttachmentObject:(Attachment * _Nonnull)value;
- (void)addAttachment:(NSSet * _Nonnull)values;
- (void)removeAttachment:(NSSet * _Nonnull)values;
@end


@interface TicketComment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable commentedTime;
@property (nonatomic, copy) NSString * _Nullable commenterId;
@property (nonatomic, copy) NSString * _Nullable commenterName;
@property (nonatomic, copy) NSString * _Nullable commenterphotoURL;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSDate * _Nullable modifiedTimeDate;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSSet * _Nullable attachment;
@property (nonatomic, strong) Ticket * _Nullable ticket;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket12TicketThread")
@interface TicketThread : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface TicketThread (SWIFT_EXTENSION(ZohoDeskPortalTicket))
- (void)addAttachmentObject:(Attachment * _Nonnull)value;
- (void)removeAttachmentObject:(Attachment * _Nonnull)value;
- (void)addAttachment:(NSSet * _Nonnull)values;
- (void)removeAttachment:(NSSet * _Nonnull)values;
@end


@interface TicketThread (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSDate * _Nullable createdTimeDate;
@property (nonatomic, copy) NSString * _Nullable direction;
@property (nonatomic, copy) NSString * _Nullable fromEmail;
@property (nonatomic) BOOL hasAttach;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) BOOL isDraft;
@property (nonatomic, copy) NSString * _Nullable responderName;
@property (nonatomic, copy) NSString * _Nullable responderPhotoURL;
@property (nonatomic, copy) NSString * _Nullable responsderId;
@property (nonatomic, copy) NSString * _Nullable summary;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSSet * _Nullable attachment;
@property (nonatomic, strong) Ticket * _Nullable ticket;
@end





SWIFT_CLASS("_TtC20ZohoDeskPortalTicket23ZDCustomizedTicketField")
@interface ZDCustomizedTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket22ZDCustomizedTicketForm")
@interface ZDCustomizedTicketForm : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ZDPDepartment")
@interface ZDPDepartment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZDPDepartment (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, copy) NSString * _Nullable deptDescription;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable nameInCustomerPortal;
@property (nonatomic) int16_t order;
@property (nonatomic, copy) NSString * _Nullable photoURL;
@end



SWIFT_CLASS("_TtC20ZohoDeskPortalTicket22ZDPTicketConfiguration")
@interface ZDPTicketConfiguration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ZDPTicketConfiguration * _Nonnull configure;)
+ (ZDPTicketConfiguration * _Nonnull)configure SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfigure:(ZDPTicketConfiguration * _Nonnull)value;
@property (nonatomic) BOOL isReplyAllowed;
@property (nonatomic) BOOL isCommentAllowed;
@property (nonatomic) BOOL isTicketUpdateAllowed;
@property (nonatomic) BOOL isCommentEditAllowed;
@property (nonatomic) BOOL isCommentDeleteAllowed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ZDPTicketField")
@interface ZDPTicketField : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface ZDPTicketField (SWIFT_EXTENSION(ZohoDeskPortalTicket))
@property (nonatomic, strong) NSObject * _Nullable allowedValues;
@property (nonatomic, strong) NSObject * _Nullable allowedValuesServer;
@property (nonatomic, copy) NSString * _Nullable apiName;
@property (nonatomic, copy) NSString * _Nullable captchaURL;
@property (nonatomic) int16_t decimals;
@property (nonatomic, copy) NSString * _Nullable defaultValue;
@property (nonatomic, copy) NSString * _Nullable departmentID;
@property (nonatomic, strong) NSObject * _Nullable dependency;
@property (nonatomic, copy) NSString * _Nullable displayLabel;
@property (nonatomic, copy) NSString * _Nullable fieldName;
@property (nonatomic) int16_t fieldOrder;
@property (nonatomic, copy) NSString * _Nullable i18NLabel;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable initialValue;
@property (nonatomic, copy) NSString * _Nullable initialValueByClient;
@property (nonatomic) BOOL isCustomField;
@property (nonatomic) BOOL isMandatory;
@property (nonatomic) BOOL isMandatoryForLocal;
@property (nonatomic) BOOL isReadOnly;
@property (nonatomic) BOOL isReadOnlyByClient;
@property (nonatomic) BOOL isValueChanged;
@property (nonatomic) BOOL isVisible;
@property (nonatomic) BOOL isVisibleByClient;
@property (nonatomic) int32_t maxLength;
@property (nonatomic, copy) NSDate * _Nullable modifiedDate;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t precison;
@property (nonatomic, strong) NSObject * _Nullable restoreOnReplyValues;
@property (nonatomic, copy) NSString * _Nullable roundingOption;
@property (nonatomic, copy) NSString * _Nullable sectionName;
@property (nonatomic) int16_t sectionOrder;
@property (nonatomic) BOOL showField;
@property (nonatomic) BOOL showSection;
@property (nonatomic, copy) NSString * _Nullable sortBy;
@property (nonatomic, strong) NSObject * _Nullable statusMapping;
@property (nonatomic, copy) NSString * _Nullable toolTip;
@property (nonatomic, copy) NSString * _Nullable toolTipType;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable uploadAttachment;
@property (nonatomic, copy) NSString * _Nullable userInput;
@property (nonatomic, copy) NSString * _Nullable validationError;
@end

@class ZDPTicket;
@class UIViewController;
@class ZDVisibleTicketField;

SWIFT_CLASS("_TtC20ZohoDeskPortalTicket20ZDPortalSubmitTicket")
@interface ZDPortalSubmitTicket : NSObject
+ (void)showAddTicketFormWithTitle:(NSString * _Nullable)title navigationMode:(enum ZDPNavigationMode)navigationMode completion:(void (^ _Nonnull)(ZDPTicket * _Nonnull))completion onError:(void (^ _Nonnull)(NSError * _Nullable))onError;
+ (void)showWithTitle:(NSString * _Nullable)title navigationMode:(enum ZDPNavigationMode)navigationMode;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIViewController * _Nonnull viewController;)
+ (UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
+ (void)setFieldsListTobeShownWithFields:(NSArray<ZDVisibleTicketField *> * _Nonnull)fields;
+ (void)preFillTicketFieldsForForms:(NSArray<ZDCustomizedTicketForm *> * _Nonnull)forms;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket14ZDPortalTicket")
@interface ZDPortalTicket : NSObject
+ (void)showWithTitle:(NSString * _Nullable)title navigationMode:(enum ZDPNavigationMode)navigationMode;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIViewController * _Nonnull viewController;)
+ (UIViewController * _Nonnull)viewController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20ZohoDeskPortalTicket20ZDVisibleTicketField")
@interface ZDVisibleTicketField : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
