#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef ZOHODESKPORTALAPIKIT_SWIFT_H
#define ZOHODESKPORTALAPIKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZohoDeskPortalAPIKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSInteger, APNSmode, open) {
  APNSmodeSandbox = 0,
  APNSmodeProduction = 1,
};

SWIFT_CLASS_NAMED("Article")
@interface ZohoDeskPortalSDKArticle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@class ZDPArticleDetail;
@class NSError;
@class ZDPArticle;
@class ZDPArticleAttachment;
@class NSData;
@class KBFeedback;
@class CategoryDetail;
@class ZDPArticleComment;
@interface ZohoDeskPortalSDKArticle (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
+ (void)getForID:(NSString * _Nonnull)articleID locale:(NSString * _Nullable)locale with:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(ZDPArticleDetail * _Nullable, NSError * _Nullable))handler;
+ (void)getList:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPArticle *> * _Nullable, NSError * _Nullable))handler;
+ (void)getWithLink:(NSString * _Nonnull)permalink onCompletion:(void (^ _Nonnull)(ZDPArticleDetail * _Nullable, NSError * _Nullable))handler;
+ (void)getRelatedForArticleID:(NSString * _Nonnull)articleID inLocale:(NSString * _Nonnull)locale :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPArticle *> * _Nullable, NSError * _Nullable))handler;
+ (void)getAttachmentsForArticleID:(NSString * _Nonnull)articleID inLocale:(NSString * _Nullable)locale :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPArticleAttachment *> * _Nullable, NSError * _Nullable))handler;
+ (void)getContentOfAttachmentID:(NSString * _Nonnull)attachmentID inArticleID:(NSString * _Nonnull)articleID inLocale:(NSString * _Nonnull)locale :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))handler;
+ (void)like:(NSString * _Nonnull)articleID locale:(NSString * _Nonnull)locale onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)dislike:(NSString * _Nonnull)articleID locale:(NSString * _Nonnull)locale onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)post:(KBFeedback * _Nonnull)feedback forArticleID:(NSString * _Nonnull)articleID inLocale:(NSString * _Nonnull)locale onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)search:(NSString * _Nonnull)keyword inCategoryID:(NSString * _Nullable)categoryID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPArticle *> * _Nullable, NSError * _Nullable))handler;
+ (void)getCategoriesForCategoryID:(NSString * _Nonnull)categoryID with:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<CategoryDetail *> * _Nullable, NSError * _Nullable))handler;
+ (void)getCategoriesByPermalink:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(CategoryDetail * _Nullable, NSError * _Nullable))handler;
+ (void)getCategoryTreeForCategoryId:(NSString * _Nonnull)categoryId with:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(CategoryDetail * _Nullable, NSError * _Nullable))handler;
+ (void)getArticleCommentsForArticleId:(NSString * _Nonnull)articleId andLocale:(NSString * _Nonnull)locale params:(NSDictionary<NSString *, id> * _Nonnull)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPArticleComment *> * _Nullable, NSError * _Nullable))handler;
@end

SWIFT_CLASS_NAMED("Community")
@interface ZohoDeskPortalSDKCommunity : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ZDPCommunityCategoryDetail;
@class ZDPTopic;
@class TopicData;
@class Drafts;
@class TopicComment;
@class ZDPCommunityCommentData;
@protocol ZDPUploaderDelegate;
@class ZDPAttachment;
@class TopicPreferences;
@class ZDPUser;
@interface ZohoDeskPortalSDKCommunity (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
+ (void)getCategoriesOnCompletion:(void (^ _Nonnull)(NSArray<ZDPCommunityCategoryDetail *> * _Nullable, NSError * _Nullable))handler;
+ (void)followCategoryWithID:(NSString * _Nonnull)categoryID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)unfollowCategoryWithID:(NSString * _Nonnull)categoryID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)getTopics:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPTopic *> * _Nullable, NSError * _Nullable))handler;
+ (void)getMostDisuccedTopics:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPTopic *> * _Nullable, NSError * _Nullable))handler;
+ (void)getMostPopularTopics:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPTopic *> * _Nullable, NSError * _Nullable))handler;
+ (void)getTopicWithID:(NSString * _Nonnull)topicID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(ZDPTopic * _Nullable, NSError * _Nullable))handler;
+ (void)add:(TopicData * _Nonnull)topic :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(ZDPTopic * _Nullable, NSError * _Nullable))handler;
+ (void)moveDraftWithID:(NSString * _Nonnull)topicID toCategoryID:(NSString * _Nonnull)categoryID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)edit:(TopicData * _Nonnull)topic withID:(NSString * _Nonnull)topicID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(ZDPTopic * _Nullable, NSError * _Nullable))handler;
+ (void)followTopicWithID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)unfollowTopicWithID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)likeTopicWithID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)deleteTopicWithID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)getTopicDrafts:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(Drafts * _Nullable, NSError * _Nullable))handler;
+ (void)getCommentsOfTopicID:(NSString * _Nonnull)topicID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<TopicComment *> * _Nullable, NSError * _Nullable))handler;
+ (void)postComment:(ZDPCommunityCommentData * _Nonnull)comment forTopicID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(TopicComment * _Nullable, NSError * _Nullable))handler;
+ (void)updateComment:(ZDPCommunityCommentData * _Nonnull)comment withID:(NSString * _Nonnull)id forTopicID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(TopicComment * _Nullable, NSError * _Nullable))handler;
+ (void)deleteCommentWithID:(NSString * _Nonnull)id forTopicID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)postReply:(ZDPCommunityCommentData * _Nonnull)data forCommentID:(NSString * _Nonnull)commentID inTopicID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(TopicComment * _Nullable, NSError * _Nullable))handler;
+ (void)updateReply:(ZDPCommunityCommentData * _Nonnull)comment withID:(NSString * _Nonnull)id forCommentID:(NSString * _Nonnull)commentID inTopicID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(TopicComment * _Nullable, NSError * _Nullable))handler;
+ (void)deleteReplyWithID:(NSString * _Nonnull)id forCommentID:(NSString * _Nonnull)commentID inTopicID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)addAttachmentWith:(NSData * _Nonnull)data andName:(NSString * _Nonnull)fileName using:(id <ZDPUploaderDelegate> _Nullable)delegate onCompletion:(void (^ _Nonnull)(ZDPAttachment * _Nullable, NSError * _Nullable))handler;
+ (void)deleteAttachmentWithID:(NSString * _Nonnull)attachmentID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)getContentOfAttachmentID:(NSString * _Nonnull)attachmentID forCommentID:(NSString * _Nullable)commentID inTopicID:(NSString * _Nonnull)topicID onCompletion:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))handler;
+ (void)searchTopicsWithKeyword:(NSString * _Nonnull)keyword otherParams:(NSDictionary<NSString *, id> * _Nullable)otherParams onCompletion:(void (^ _Nonnull)(NSArray<ZDPTopic *> * _Nullable, NSError * _Nullable))handler;
+ (void)getPreferencesOnCompletion:(void (^ _Nonnull)(TopicPreferences * _Nullable, NSError * _Nullable))handler;
+ (void)getTopicWithPermaLink:(NSString * _Nonnull)permaLink :(NSDictionary<NSString *, id> * _Nullable)params handler:(void (^ _Nonnull)(ZDPTopic * _Nullable, NSError * _Nullable))handler;
+ (void)getCommunityCategoryWithCategoryId:(NSString * _Nonnull)categoryId handler:(void (^ _Nonnull)(ZDPCommunityCategoryDetail * _Nullable, NSError * _Nullable))handler;
+ (void)getTopContributorsWithParams:(NSDictionary<NSString *, id> * _Nullable)params handler:(void (^ _Nonnull)(NSArray<ZDPUser *> * _Nullable, NSError * _Nullable))handler;
+ (void)getParticipantsOfTopic:(NSString * _Nonnull)topicID params:(NSDictionary<NSString *, id> * _Nullable)params handler:(void (^ _Nonnull)(NSArray<ZDPUser *> * _Nullable, NSError * _Nullable))handler;
+ (void)getUnRepliedTopicsWithParams:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPTopic *> * _Nullable, NSError * _Nullable))handler;
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit10PEDefaults")
@interface PEDefaults : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit24SearchEngineOptimisation")
@interface SearchEngineOptimisation : NSObject
@property (nonatomic, copy) NSString * _Nullable keywords;
@property (nonatomic, copy) NSString * _Nullable seoDescription;
@property (nonatomic, copy) NSString * _Nullable title;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("Ticket")
@interface ZohoDeskPortalSDKTicket : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FormLayout;
@class TicketForm;
@class Template;
@class ZDTicketField;
@class LayoutRule;
@class ValidationRule;
@class ZDPTicket;
@class Resolution;
@interface ZohoDeskPortalSDKTicket (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
+ (void)getLayouts:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<FormLayout *> * _Nullable, NSError * _Nullable))handler;
+ (void)getForm:(NSDictionary<NSString *, id> * _Nullable)params headers:(NSDictionary<NSString *, NSString *> * _Nullable)headers onCompletion:(void (^ _Nonnull)(TicketForm * _Nullable, NSError * _Nullable))handler;
+ (void)getTemplates:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<Template *> * _Nullable, NSError * _Nullable))handler;
+ (void)getTemplateWithID:(NSString * _Nonnull)templateID onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
+ (void)getFields:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDTicketField *> * _Nullable, NSError * _Nullable))handler;
+ (void)getLayoutRulesWithParams:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<LayoutRule *> * _Nullable, NSError * _Nullable))handler;
+ (void)getValidationRulesWithParams:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ValidationRule *> * _Nullable, NSError * _Nullable))handler;
+ (void)addWithFields:(NSDictionary<NSString *, id> * _Nonnull)fields onCompletion:(void (^ _Nonnull)(ZDPTicket * _Nullable, NSError * _Nullable))handler;
+ (void)updateTicketWithID:(NSString * _Nonnull)id params:(NSDictionary<NSString *, id> * _Nonnull)params onCompletion:(void (^ _Nonnull)(ZDPTicket * _Nullable, NSError * _Nullable))handler;
+ (void)getList:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPTicket *> * _Nullable, NSError * _Nullable))handler;
+ (void)getAttachmentForID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSArray<ZDPAttachment *> * _Nullable, NSError * _Nullable))handler;
+ (void)searchTickets:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPTicket *> * _Nullable, NSError * _Nullable))handler;
+ (void)getForID:(NSString * _Nonnull)ticketID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(ZDPTicket * _Nullable, NSError * _Nullable))handler;
+ (void)getThreadsForTicketID:(NSString * _Nonnull)ticketID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<NSDictionary<NSString *, id> *> * _Nullable, NSError * _Nullable))handler;
+ (void)getThreadWithID:(NSString * _Nonnull)threadID forTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
+ (void)reply:(NSDictionary<NSString *, id> * _Nonnull)thread toTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
+ (void)edit:(NSDictionary<NSString *, id> * _Nonnull)thread withID:(NSString * _Nonnull)threadID inTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
+ (void)getConversationsForTicketID:(NSString * _Nonnull)ticketID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<NSDictionary<NSString *, id> *> * _Nullable, NSError * _Nullable))handler;
+ (void)getCommentsForTicketID:(NSString * _Nonnull)ticketID :(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<NSDictionary<NSString *, id> *> * _Nullable, NSError * _Nullable))handler;
+ (void)add:(NSDictionary<NSString *, id> * _Nonnull)comment toTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
+ (void)edit:(NSDictionary<NSString *, id> * _Nonnull)comment withID:(NSString * _Nonnull)commentID toTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, NSError * _Nullable))handler;
+ (void)addAttachmentWith:(NSData * _Nonnull)data andName:(NSString * _Nonnull)fileName using:(id <ZDPUploaderDelegate> _Nullable)delegate onCompletion:(void (^ _Nonnull)(ZDPAttachment * _Nullable, NSError * _Nullable))handler;
+ (void)deleteAttachmentWithID:(NSString * _Nonnull)attachmentID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)getContentOfAttachmentID:(NSString * _Nonnull)attachmentID forCommentID:(NSString * _Nonnull)commentID inTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))handler;
+ (void)getContentOfAttachmentID:(NSString * _Nonnull)attachmentID forthreadID:(NSString * _Nonnull)threadID inTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))handler;
+ (void)deleteCommentWithID:(NSString * _Nonnull)commentID forTicketID:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)getResolution:(NSString * _Nonnull)ticketID onCompletion:(void (^ _Nonnull)(Resolution * _Nullable, NSError * _Nullable))handler;
@end

@class ZDPArticleCategory;
SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit10ZDPArticle")
@interface ZDPArticle : NSObject
@property (nonatomic, strong) ZDPArticleCategory * _Nullable category;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nonnull webURL;
@property (nonatomic, copy) NSString * _Nonnull translationID;
@property (nonatomic, copy) NSString * _Nonnull rootCategoryID;
@property (nonatomic, copy) NSString * _Nonnull locale;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ZDPArticle (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

@interface ZDPArticle (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit10ZDPArticle14CategoryDetail")
@interface CategoryDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable articlesCount;
@property (nonatomic, copy) NSString * _Nullable sectionsCount;
@property (nonatomic, copy) NSString * _Nullable translatedName;
@property (nonatomic, copy) NSString * _Nullable logoURL;
@property (nonatomic, copy) NSString * _Nullable articleViewType;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull visibility;
@property (nonatomic, copy) NSString * _Nullable permalink;
@property (nonatomic, copy) NSString * _Nullable webURL;
@property (nonatomic, copy) NSString * _Nullable locale;
@property (nonatomic, copy) NSString * _Nullable categoryDescription;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable parentCategoryID;
@property (nonatomic, copy) NSString * _Nullable allArticleCount;
@property (nonatomic, copy) NSString * _Nullable rootCategoryId;
/// Identifiers of the departments associated with this category
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull associatedDepartments;
@property (nonatomic, copy) NSArray<CategoryDetail *> * _Nonnull subCategories;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit10ZDPArticle10KBFeedback")
@interface KBFeedback : NSObject
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nullable email;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit20ZDPArticleAttachment")
@interface ZDPArticleAttachment : NSObject
@property (nonatomic, copy) NSString * _Nonnull contentURL;
@property (nonatomic, copy) NSString * _Nonnull size;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nullable createdTime;
@property (nonatomic, copy) NSString * _Nonnull inlineURL;
@property (nonatomic, copy) NSString * _Nonnull id;
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit18ZDPArticleCategory")
@interface ZDPArticleCategory : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable locale;
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit17ZDPArticleComment")
@interface ZDPArticleComment : NSObject
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nonnull commentedTime;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic, strong) ZDPUser * _Nonnull commenter;
@end

@class Locale;
SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit16ZDPArticleDetail")
@interface ZDPArticleDetail : NSObject
@property (nonatomic, copy) NSString * _Nonnull modifiedTime;
@property (nonatomic, copy) NSString * _Nullable myVote;
@property (nonatomic, strong) ZDPUser * _Nullable author;
@property (nonatomic, copy) NSString * _Nonnull departmentID;
@property (nonatomic, copy) NSString * _Nonnull dislikeCount;
@property (nonatomic, copy) NSString * _Nonnull likeCount;
@property (nonatomic, copy) NSString * _Nonnull commentCount;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull tags;
@property (nonatomic, copy) NSString * _Nonnull answer;
@property (nonatomic, copy) NSString * _Nonnull webURL;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull permalink;
@property (nonatomic, strong) SearchEngineOptimisation * _Nullable seo;
@property (nonatomic, copy) NSString * _Nonnull categoryID;
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic, copy) NSString * _Nonnull locale;
@property (nonatomic, copy) NSString * _Nonnull rootCategoryID;
@property (nonatomic, copy) NSString * _Nonnull translationID;
@property (nonatomic, strong) ZDPArticleCategory * _Nonnull category;
/// add include=locales param in get transaltion API to get this value
@property (nonatomic, copy) NSArray<Locale *> * _Nullable locales;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit16ZDPArticleDetail6Locale")
@interface Locale : NSObject
@property (nonatomic, copy) NSString * _Nonnull apiURL;
@property (nonatomic, copy) NSString * _Nonnull webURL;
@property (nonatomic, copy) NSString * _Nonnull permalink;
@property (nonatomic, copy) NSString * _Nonnull locale;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit10ZDPCTicket")
@interface ZDPCTicket : NSObject
@property (nonatomic, copy) NSString * _Nonnull number;
@property (nonatomic, copy) NSString * _Nonnull id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZDPCTopicType, open) {
  ZDPCTopicTypeQuestion = 0,
  ZDPCTopicTypeProblem = 1,
  ZDPCTopicTypeIdea = 2,
  ZDPCTopicTypeDiscussion = 3,
  ZDPCTopicTypeAnnouncement = 4,
};

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit12ZDPCommunity")
@interface ZDPCommunity : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface ZDPCommunity (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity9TopicData")
@interface TopicData : NSObject
@property (nonatomic, copy) NSString * _Nonnull categoryID;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable attachmentIDs;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic) enum ZDPCTopicType topicType;
@property (nonatomic) BOOL isDraft;
@property (nonatomic) BOOL notifyMe;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity10DraftTopic")
@interface DraftTopic : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nonnull type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ZDPMentions;
@class ZDPTag;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity8ZDPTopic")
@interface ZDPTopic : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic, strong) ZDPUser * _Nonnull creator;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, copy) NSString * _Nonnull label;
@property (nonatomic, copy) NSString * _Nonnull permalink;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nullable commentCount;
@property (nonatomic, copy) NSString * _Nullable likeCount;
@property (nonatomic, readonly) BOOL isVoted;
@property (nonatomic, copy) NSString * _Nonnull categoryID;
@property (nonatomic, strong) ZDPUser * _Nullable lastCommenter;
@property (nonatomic, copy) NSString * _Nullable latestCommentTime;
@property (nonatomic, copy) NSString * _Nullable webUrl;
@property (nonatomic, copy) NSString * _Nullable bestCommentId;
@property (nonatomic, strong) ZDPMentions * _Nullable mentions;
@property (nonatomic, copy) NSArray<ZDPAttachment *> * _Nonnull attachments;
@property (nonatomic, copy) NSString * _Nullable viewCount;
@property (nonatomic, copy) NSString * _Nullable followersCount;
@property (nonatomic, readonly) BOOL isFollowing;
@property (nonatomic, readonly) BOOL isSticky;
@property (nonatomic, readonly) BOOL isDraft;
@property (nonatomic, readonly) BOOL isLocked;
@property (nonatomic, readonly) BOOL notifyMe;
@property (nonatomic, strong) ZDPCTicket * _Nullable ticket;
@property (nonatomic, copy) NSArray<ZDPTag *> * _Nonnull tags;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Trend;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity17TopicCommentTrend")
@interface TopicCommentTrend : NSObject
@property (nonatomic, copy) NSArray<Trend *> * _Nonnull commentTrend;
@property (nonatomic, copy) NSArray<Trend *> * _Nonnull postTrend;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity5Trend")
@interface Trend : NSObject
@property (nonatomic, copy) NSString * _Nonnull date;
@property (nonatomic, copy) NSString * _Nonnull count;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity9GameLevel")
@interface GameLevel : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull id;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity13GameNextLevel")
@interface GameNextLevel : NSObject
@property (nonatomic, copy) NSString * _Nonnull pointsToReach;
@property (nonatomic, copy) NSString * _Nonnull name;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity16GameAchievements")
@interface GameAchievements : NSObject
@property (nonatomic, copy) NSString * _Nonnull badgeCount;
@property (nonatomic, copy) NSString * _Nonnull points;
@property (nonatomic, strong) GameLevel * _Nullable level;
@property (nonatomic, strong) GameNextLevel * _Nullable nextLevel;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity6Badges")
@interface Badges : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull badgesDescription;
@property (nonatomic, copy) NSString * _Nullable iconUrl;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity10ScoreBoard")
@interface ScoreBoard : NSObject
@property (nonatomic, copy) NSString * _Nonnull pointsEarned;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull scoreBoardDescription;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity6ZDPTag")
@interface ZDPTag : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull permalink;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity12TopicComment")
@interface TopicComment : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nullable topicId;
@property (nonatomic, copy) NSString * _Nullable subject;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable topicPermalink;
@property (nonatomic, copy) NSArray<ZDPAttachment *> * _Nonnull attachments;
@property (nonatomic, strong) ZDPUser * _Nonnull creator;
@property (nonatomic, copy) NSArray<TopicComment *> * _Nonnull replies;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity16TopicPreferences")
@interface TopicPreferences : NSObject
@property (nonatomic, copy) NSString * _Nonnull defaultTopicType;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull topicTypes;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity6Drafts")
@interface Drafts : NSObject
@property (nonatomic, copy) NSArray<DraftTopic *> * _Nonnull data;
@property (nonatomic, copy) NSString * _Nonnull count;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit12ZDPCommunity21ParticipantStatistics")
@interface ParticipantStatistics : NSObject
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit20ZDPCommunityCategory")
@interface ZDPCommunityCategory : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable photoUrl;
@property (nonatomic, copy) NSString * _Nullable categoryDescription;
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit26ZDPCommunityCategoryDetail")
@interface ZDPCommunityCategoryDetail : NSObject
@property (nonatomic) BOOL isFollowing;
@property (nonatomic, copy) NSString * _Nonnull categoryDescription;
@property (nonatomic, copy) NSString * _Nonnull commentCount;
@property (nonatomic, copy) NSString * _Nullable photoURL;
@property (nonatomic) BOOL isLocked;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull postCount;
@property (nonatomic, copy) NSString * _Nullable parentCategoryID;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull position;
@property (nonatomic, copy) NSString * _Nonnull followersCount;
@property (nonatomic, copy) NSString * _Nonnull permalink;
@property (nonatomic, copy) NSArray<ZDPCommunityCategoryDetail *> * _Nonnull subCategories;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull permissions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit23ZDPCommunityCommentData")
@interface ZDPCommunityCommentData : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull attachmentIDs;
@property (nonatomic, copy) NSString * _Nonnull content;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZDPDataCenter, open) {
  ZDPDataCenterUS = 0,
  ZDPDataCenterCN = 1,
  ZDPDataCenterIN = 2,
  ZDPDataCenterEU = 3,
  ZDPDataCenterAU = 4,
  ZDPDataCenterJP = 5,
  ZDPDataCenterCA = 6,
  ZDPDataCenterSA = 7,
  ZDPDataCenterSG = 8,
  ZDPDataCenterINEC = 9,
  ZDPDataCenterUAE = 10,
};

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit11ZDPDefaults")
@interface ZDPDefaults : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Provide conformace to this protocol to log messages your preferred way
SWIFT_PROTOCOL("_TtP20ZohoDeskPortalAPIKit11ZDPLoggable_")
@protocol ZDPLoggable
/// log the given string in your preferred location
/// \param message the string which is to be logged
///
- (void)log:(NSString * _Nonnull)message;
@end

@class LayoutDetails;
@class ZDPAccount;
@class ZDPProduct;
SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit9ZDPTicket")
@interface ZDPTicket : NSObject
@property (nonatomic, copy) NSString * _Nonnull ticketNumber;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
@property (nonatomic, strong) ZDPUser * _Nullable creator;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nullable dueDate;
@property (nonatomic, copy) NSString * _Nonnull departmentID;
@property (nonatomic, copy) NSString * _Nonnull threadCount;
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable onholdTime;
@property (nonatomic, copy) NSString * _Nullable priority;
@property (nonatomic, copy) NSString * _Nullable closedTime;
@property (nonatomic, strong) ZDPUser * _Nullable assignee;
@property (nonatomic, copy) NSString * _Nonnull commentCount;
@property (nonatomic, copy) NSString * _Nonnull createdTime;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable secondaryContacts;
@property (nonatomic, copy) NSString * _Nullable tickeDescription;
@property (nonatomic, copy) NSString * _Nullable resolution;
@property (nonatomic, copy) NSString * _Nullable responseDueDate;
@property (nonatomic, strong) ZDPUser * _Nullable modifiedBy;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable productID;
@property (nonatomic, copy) NSString * _Nullable contactID;
@property (nonatomic, copy) NSString * _Nullable classification;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic, copy) NSString * _Nullable teamID;
@property (nonatomic, strong) LayoutDetails * _Nullable layoutDetails;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic, copy) NSString * _Nullable subCategory;
@property (nonatomic, strong) ZDPAccount * _Nullable account;
@property (nonatomic, strong) ZDPProduct * _Nullable product;
@property (nonatomic) BOOL hasBlueprint;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ZDPTicket (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

@class LayoutFD;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket10LayoutRule")
@interface LayoutRule : NSObject
@property (nonatomic, readonly, copy) NSArray<LayoutFD *> * _Nonnull fieldConditions;
@property (nonatomic, readonly, copy) NSString * _Nonnull modifiedTime;
@property (nonatomic, readonly, copy) NSString * _Nonnull fieldName;
@property (nonatomic, readonly, copy) NSString * _Nonnull createdBy;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull datumDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull createdTime;
@property (nonatomic, readonly, copy) NSString * _Nonnull modifiedBy;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull layoutID;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ValidationFD;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket14ValidationRule")
@interface ValidationRule : NSObject
@property (nonatomic, readonly, copy) NSArray<ValidationFD *> * _Nonnull fieldConditions;
@property (nonatomic, readonly, copy) NSString * _Nonnull modifiedTime;
@property (nonatomic, readonly, copy) NSString * _Nonnull fieldName;
@property (nonatomic, readonly, copy) NSString * _Nonnull createdBy;
@property (nonatomic, readonly, copy) NSString * _Nonnull createdTime;
@property (nonatomic, readonly, copy) NSString * _Nonnull modifiedBy;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull layoutID;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class RuleCondition;
@class LayoutActions;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket8LayoutFD")
@interface LayoutFD : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull pattern;
@property (nonatomic, readonly, copy) NSArray<RuleCondition *> * _Nonnull conditions;
@property (nonatomic, readonly, strong) LayoutActions * _Nonnull actions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ValidationActions;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket12ValidationFD")
@interface ValidationFD : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull pattern;
@property (nonatomic, readonly, copy) NSArray<RuleCondition *> * _Nonnull conditions;
@property (nonatomic, readonly, strong) ValidationActions * _Nonnull actions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket13LayoutActions")
@interface LayoutActions : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull showSections;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull showFields;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull setMandatoryFields;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket17ValidationActions")
@interface ValidationActions : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull alert;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket13RuleCondition")
@interface RuleCondition : NSObject
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull displayValue;
@property (nonatomic, readonly, copy) NSString * _Nonnull condition;
@property (nonatomic, readonly, copy) NSString * _Nonnull fieldName;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ZDPTicket (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

@class CountbyStatus;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket15StatusTypeCount")
@interface StatusTypeCount : NSObject
@property (nonatomic, copy) NSArray<CountbyStatus *> * _Nullable statusType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket13CountbyStatus")
@interface CountbyStatus : NSObject
@property (nonatomic, copy) NSString * _Nullable count;
@property (nonatomic, copy) NSString * _Nullable value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket7ZDPData")
@interface ZDPData : NSObject
@property (nonatomic, copy) NSString * _Nonnull departmentID;
@property (nonatomic, copy) NSString * _Nonnull subject;
@property (nonatomic, copy) NSString * _Nullable productID;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable ticketDescription;
@property (nonatomic, copy) NSString * _Nullable priority;
@property (nonatomic, copy) NSString * _Nullable classification;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FormSection;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket10TicketForm")
@interface TicketForm : NSObject
@property (nonatomic, copy) NSArray<FormSection *> * _Nonnull sections;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket11FormSection")
@interface FormSection : NSObject
@property (nonatomic, copy) NSString * _Nonnull sectionName;
@property (nonatomic, copy) NSArray<ZDTicketField *> * _Nonnull fields;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class StatusMap;
SWIFT_CLASS_NAMED("TicketField")
@interface ZDTicketField : NSObject
@property (nonatomic, copy) NSString * _Nullable displayLabel;
@property (nonatomic, copy) NSString * _Nullable i18NLabel;
@property (nonatomic, copy) NSString * _Nullable apiName;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic) BOOL isMandatory;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable allowedValues;
@property (nonatomic, copy) NSDictionary<NSString *, NSDictionary<NSString *, NSArray<NSString *> *> *> * _Nullable dependency;
@property (nonatomic, copy) NSString * _Nullable defaultValue;
@property (nonatomic, copy) NSString * _Nullable toolTip;
@property (nonatomic, copy) NSString * _Nullable toolTipType;
@property (nonatomic, copy) NSString * _Nullable sortBy;
@property (nonatomic, copy) NSArray<StatusMap *> * _Nullable statusMapping;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable restoreOnReplyValues;
@property (nonatomic, copy) NSString * _Nullable roundingOption;
@property (nonatomic, copy) NSString * _Nullable fieldName;
@property (nonatomic, copy) NSString * _Nullable uploadAttachment;
@property (nonatomic, copy) NSString * _Nullable captchaURL;
@property (nonatomic) BOOL isPHI;
@property (nonatomic) BOOL isEncryptedField;
@property (nonatomic) BOOL isNested;
@property (nonatomic, copy) NSString * _Nullable audioCaptchaurl;
@property (nonatomic, copy) NSString * _Nullable imageCaptchaurl;
@property (nonatomic) BOOL isVisible;
@property (nonatomic) NSInteger maxLength;
@property (nonatomic) NSInteger precison;
@property (nonatomic) NSInteger decimals;
@property (nonatomic) BOOL isReadOnly;
@property (nonatomic) BOOL isCustomField;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket9StatusMap")
@interface StatusMap : NSObject
@property (nonatomic, copy) NSString * _Nonnull mappingValue;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket8Template")
@interface Template : NSObject
@property (nonatomic, copy) NSString * _Nonnull ticketTemplateName;
@property (nonatomic, copy) NSString * _Nonnull id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket10Resolution")
@interface Resolution : NSObject
@property (nonatomic, strong) ZDPUser * _Nullable modifiedBy;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable modifiedTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket14TemplateDetail")
@interface TemplateDetail : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable customFields;
@property (nonatomic, copy) NSString * _Nullable productID;
@property (nonatomic, copy) NSString * _Nullable contactID;
@property (nonatomic, copy) NSString * _Nullable subject;
@property (nonatomic, copy) NSString * _Nonnull departmentID;
@property (nonatomic, copy) NSString * _Nullable dueDate;
@property (nonatomic, copy) NSString * _Nullable channel;
@property (nonatomic, copy) NSString * _Nullable templateDescription;
@property (nonatomic, copy) NSString * _Nonnull priority;
@property (nonatomic, copy) NSString * _Nullable assigneeID;
@property (nonatomic, copy) NSString * _Nullable resolution;
@property (nonatomic, copy) NSString * _Nullable teamID;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CommentContentType, open) {
  CommentContentTypeHtml = 0,
  CommentContentTypePlainText = 1,
};

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket10FormLayout")
@interface FormLayout : NSObject
@property (nonatomic, copy) NSString * _Nonnull departmentID;
@property (nonatomic) BOOL hasLogo;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL isDefaultLayout;
@property (nonatomic) BOOL isStandardLayout;
@property (nonatomic, copy) NSString * _Nonnull layoutDesc;
@property (nonatomic, copy) NSString * _Nonnull layoutName;
@property (nonatomic, copy, getter=module, setter=setModule:) NSString * _Nonnull module_;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket12AudioCaptcha")
@interface AudioCaptcha : NSObject
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket16AudioCaptchaData")
@interface AudioCaptchaData : NSObject
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket12ImageCaptcha")
@interface ImageCaptcha : NSObject
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit9ZDPTicket16ImageCaptchaData")
@interface ImageCaptchaData : NSObject
@end

/// conform to the delegate to know the status of file which you upload
SWIFT_PROTOCOL("_TtP20ZohoDeskPortalAPIKit19ZDPUploaderDelegate_")
@protocol ZDPUploaderDelegate
/// the delegate method is called when each part of file is uploaded
/// \param fraction the total fraction of the file uploaded (it is always a value between 0 and 1)
///
- (void)uploadedWithFraction:(float)fraction;
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit8ZDPortal")
@interface ZDPortal : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface ZDPortal (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10WidgetCard")
@interface WidgetCard : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable content;
- (nonnull instancetype)initWithInitializer:(SWIFT_NOESCAPE void (^ _Nonnull)(WidgetCard * _Nonnull))initializer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ZDPortal (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

@class ZDPEmail;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10ZDPProfile")
@interface ZDPProfile : NSObject
@property (nonatomic, copy) NSString * _Nonnull displayName;
@property (nonatomic, copy) NSString * _Nullable facebook;
@property (nonatomic, copy) NSString * _Nullable mobile;
@property (nonatomic, copy) NSString * _Nonnull timeZone;
@property (nonatomic, copy) NSString * _Nonnull fullName;
@property (nonatomic, copy) NSString * _Nonnull emailID;
@property (nonatomic, copy) NSString * _Nonnull countryLocale;
@property (nonatomic, copy) NSString * _Nullable photoURL;
@property (nonatomic, copy) NSString * _Nullable twitter;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable joiningTime;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull groupIDS;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSArray<ZDPEmail *> * _Nonnull email;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal8ZDPEmail")
@interface ZDPEmail : NSObject
@property (nonatomic, copy) NSString * _Nonnull emailAddress;
@property (nonatomic) BOOL isVerified;
@property (nonatomic) BOOL isPrimary;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10Department")
@interface Department : NSObject
@property (nonatomic, copy) NSString * _Nullable photoURL;
@property (nonatomic, copy) NSString * _Nullable deptDescription;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull nameInCustomerPortal;
@property (nonatomic) int64_t layoutCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal11ZDPMentions")
@interface ZDPMentions : NSObject
@property (nonatomic, copy) NSArray<ZDPUser *> * _Nonnull users;
@end

@class ZDPLabel;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal7ZDPUser")
@interface ZDPUser : NSObject
@property (nonatomic, copy) NSString * _Nullable photoURL;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable zuid;
@property (nonatomic, strong) ZDPLabel * _Nullable label;
@property (nonatomic, copy) NSString * _Nullable photoUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10ZDPProduct")
@interface ZDPProduct : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nullable departmentIDS;
@property (nonatomic, copy) NSString * _Nonnull productName;
@property (nonatomic, copy) NSString * _Nullable productDescription;
@property (nonatomic, copy) NSString * _Nullable productCode;
@property (nonatomic, copy) NSString * _Nonnull id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal13ZDPAttachment")
@interface ZDPAttachment : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull size;
@property (nonatomic, copy) NSString * _Nullable downloadURL;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10ZDPContact")
@interface ZDPContact : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable photoUrl;
@property (nonatomic, copy) NSString * _Nullable email;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10ZDPAccount")
@interface ZDPAccount : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable mappingType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface ZDPortal (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
@end

@class Preferences;
@class ASAPApp;
@class ChatKitSettings;
@class ZDPLanguage;
@class ChatKitKey;
@class BusinessHours;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal11ZDPSettings")
@interface ZDPSettings : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nullable communityRootCategoryIds;
@property (nonatomic, strong) Preferences * _Nonnull preferences;
@property (nonatomic, strong) ASAPApp * _Nonnull asapApp;
@property (nonatomic) BOOL pushNotificationConfiguration;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull rootKBCategoryIDs;
@property (nonatomic, strong) ASAPApp * _Nullable asapPreferences;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable ziaSkillSetInfo;
@property (nonatomic, copy) NSString * _Nullable ziaPortalID;
@property (nonatomic, strong) ChatKitSettings * _Nullable chatPreferences;
/// base url of the ASAP portal with name. append language string and any other path as desired.
@property (nonatomic, copy) NSString * _Nullable helpCenterURL;
@property (nonatomic, copy) NSString * _Nullable helpCenterId;
@property (nonatomic, strong) ZDPLanguage * _Nonnull primaryLocaleObj;
@property (nonatomic, copy) NSArray<ZDPLanguage *> * _Nonnull locales;
@property (nonatomic, copy) NSString * _Nonnull imDomain;
@property (nonatomic, copy) NSString * _Nonnull portalName;
@property (nonatomic, copy) NSString * _Nonnull staticVersion;
@property (nonatomic, copy) NSString * _Nullable deskDomain;
@property (nonatomic, copy) NSString * _Nonnull portalId;
@property (nonatomic, copy) NSString * _Nullable clientAuthDomain;
@property (nonatomic, copy) NSString * _Nullable staticPath;
@property (nonatomic, copy) NSString * _Nonnull appSecretId;
@property (nonatomic, copy) NSString * _Nonnull gcDomain;
@property (nonatomic, copy) NSString * _Nonnull primaryLocale;
@property (nonatomic, copy) NSString * _Nullable appId;
@property (nonatomic, strong) ChatKitKey * _Nullable chatAppKeyWithDC;
@property (nonatomic, strong) BusinessHours * _Nullable businessHours;
@property (nonatomic, copy) NSString * _Nullable forumCategoryID;
@property (nonatomic, copy) NSString * _Nullable kbCategoryID;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MobilePrivacySettings;
@class ASAPAppearance;
@class ASAPMobileChatConfig;
@class WelcomeNote;
@class Module;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal7ASAPApp")
@interface ASAPApp : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull modifiedTime;
@property (nonatomic, strong) MobilePrivacySettings * _Nullable mobilePrivacySettings;
@property (nonatomic, strong) ASAPAppearance * _Nullable botAppearence;
@property (nonatomic, strong) ASAPMobileChatConfig * _Nullable asapMobileChatConfig;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, strong) WelcomeNote * _Nonnull defaultWelcomeMessages;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable departmentId;
@property (nonatomic, copy) NSArray<Module *> * _Nonnull modules;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal11WelcomeNote")
@interface WelcomeNote : NSObject
@property (nonatomic, copy) NSString * _Nullable introMessage;
@property (nonatomic, copy) NSString * _Nullable greetingMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal21MobilePrivacySettings")
@interface MobilePrivacySettings : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull clientId;
@property (nonatomic, readonly) BOOL isJWTEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull clientSecret;
@property (nonatomic, readonly) BOOL isAnonymousEnabled;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal20ASAPMobileChatConfig")
@interface ASAPMobileChatConfig : NSObject
@property (nonatomic, copy) NSString * _Nullable chatAppKey;
@property (nonatomic, copy) NSString * _Nullable chatAccessKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ASAPMobileAppearance;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal14ASAPAppearance")
@interface ASAPAppearance : NSObject
@property (nonatomic, strong) ASAPMobileAppearance * _Nullable mobileAppAppearence;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal20ASAPMobileAppearance")
@interface ASAPMobileAppearance : NSObject
@property (nonatomic, copy) NSString * _Nonnull wallpaperUrl;
@property (nonatomic, copy) NSString * _Nonnull headerLogoUrl;
@property (nonatomic, copy) NSString * _Nonnull themeColor;
@property (nonatomic, copy) NSString * _Nonnull wallpaperType;
@property (nonatomic) BOOL showZohoTag;
@end

@class TabProperties;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal6Module")
@interface Module : NSObject
@property (nonatomic, strong) TabProperties * _Nullable tabProperties;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull clients;
@property (nonatomic, readonly, copy) NSString * _Nonnull displayName;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL status;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal13TabProperties")
@interface TabProperties : NSObject
@property (nonatomic, copy) NSString * _Nullable chatAppKey;
@property (nonatomic, copy) NSString * _Nullable chatAccessKey;
@property (nonatomic, copy) NSString * _Nullable widgetId;
@property (nonatomic, copy) NSString * _Nullable botId;
@property (nonatomic, copy) NSString * _Nullable orgId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal11ZDPLanguage")
@interface ZDPLanguage : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSString * _Nonnull localeWithRegion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal13BusinessHours")
@interface BusinessHours : NSObject
@property (nonatomic, copy) NSString * _Nonnull timeZone;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull holidayList;
@property (nonatomic) BOOL isActive;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable timeDetails;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ChatSettings;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal15ChatKitSettings")
@interface ChatKitSettings : NSObject
@property (nonatomic, strong) ChatSettings * _Nullable ios;
@property (nonatomic, strong) ChatSettings * _Nullable android;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal12ChatSettings")
@interface ChatSettings : NSObject
@property (nonatomic) NSInteger isAgentPhotoEnabled;
@property (nonatomic) NSInteger isPushNotificationEnabled;
@property (nonatomic) NSInteger isChatEnabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10ChatKitKey")
@interface ChatKitKey : NSObject
@property (nonatomic, copy) NSString * _Nullable ios;
@property (nonatomic, copy) NSString * _Nullable android;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal11Preferences")
@interface Preferences : NSObject
@property (nonatomic) BOOL isHelpCenterPublic;
@property (nonatomic) BOOL isForumsVisible;
@property (nonatomic) BOOL isSelfSignUpEnabled;
@property (nonatomic) BOOL isAccountTicketsVisible;
@property (nonatomic) BOOL isSecondaryContactsEnabled;
@property (nonatomic) BOOL isTagsVisible;
@property (nonatomic) BOOL isKBVisible;
@property (nonatomic, copy) NSString * _Nullable searchScope;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ArticleFeedbackFormConfiguration, open) {
  ArticleFeedbackFormConfigurationNone = 0,
  ArticleFeedbackFormConfigurationAnonymous = 1,
  ArticleFeedbackFormConfigurationHide = 2,
  ArticleFeedbackFormConfigurationShow = 3,
};

SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal10ZiaDetails")
@interface ZiaDetails : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ZDPPreferences;
@class Configurations;
@class ActiveLocale;
SWIFT_CLASS("_TtCC20ZohoDeskPortalAPIKit8ZDPortal21HelpCenterPreferences")
@interface HelpCenterPreferences : NSObject
@property (nonatomic, strong) ZDPPreferences * _Nonnull preferences;
@property (nonatomic, strong) Configurations * _Nonnull configurations;
@property (nonatomic, readonly, copy) NSString * _Nonnull logoLinkBackUrl;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull departmentIds;
@property (nonatomic, readonly, copy) NSArray<ActiveLocale *> * _Nonnull activeLocales;
@property (nonatomic, readonly, copy) NSString * _Nonnull locale;
@property (nonatomic, readonly, copy) NSString * _Nonnull logoUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull url;
@property (nonatomic, readonly, copy) NSString * _Nonnull accountId;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull locales;
@property (nonatomic, readonly, copy) NSString * _Nonnull portalId;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull favIconUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull primaryLocale;
@end

@class GuestUserAccessRestriction;
SWIFT_CLASS_NAMED("Preferences")
@interface ZDPPreferences : NSObject
@property (nonatomic, readonly) BOOL isAccountTicketViewable;
@property (nonatomic, readonly) BOOL isArticleUpdatedTimeVisible;
@property (nonatomic, readonly) BOOL isMultiLayoutGridViewEnabled;
@property (nonatomic, readonly) BOOL isSignUpFormCustomized;
@property (nonatomic, readonly) BOOL showFeedbackFormOnDislike;
@property (nonatomic, readonly) BOOL isArticleAuthorInfoVisible;
@property (nonatomic, readonly) BOOL isSelfSignUp;
@property (nonatomic, readonly) BOOL isCommunityEnabled;
@property (nonatomic, readonly) BOOL isTocEnabled;
@property (nonatomic, readonly) BOOL isClientDebuggingEnabled;
@property (nonatomic, readonly) BOOL isUserDeletionEnabled;
@property (nonatomic, readonly) BOOL isSEOSetAcrossAllPages;
@property (nonatomic, readonly) BOOL isHelpCenterPublic;
@property (nonatomic, readonly) BOOL isMultilingualEnabled;
@property (nonatomic, readonly) BOOL isKBEnabled;
@property (nonatomic, readonly) BOOL isSecondaryContactsEnabled;
@property (nonatomic, readonly) BOOL isOnHoldEnabled;
@property (nonatomic, readonly) BOOL isContactAccountMultiMappingEnabled;
@property (nonatomic, readonly) BOOL isOTPBasedAuthenticationEnabled;
@property (nonatomic, readonly) BOOL isGamificationEnabled;
@property (nonatomic, readonly) BOOL isTagsEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull articleFeedbackFormOnDislike;
@property (nonatomic, readonly, copy) NSString * _Nonnull tocPosition;
@property (nonatomic, readonly, copy) NSString * _Nonnull signupFormLayout;
@property (nonatomic, readonly, copy) NSString * _Nonnull searchScope;
@property (nonatomic, readonly, copy) NSString * _Nonnull communityLandingPage;
@property (nonatomic, readonly) BOOL isPayloadEncryptionEnabled;
@property (nonatomic, strong) GuestUserAccessRestriction * _Nonnull guestUserAccessRestriction;
@property (nonatomic, readonly) enum ArticleFeedbackFormConfiguration articleFeedbackFormConfiguration;
@end

SWIFT_CLASS("_TtCCCC20ZohoDeskPortalAPIKit8ZDPortal21HelpCenterPreferences11Preferences26GuestUserAccessRestriction")
@interface GuestUserAccessRestriction : NSObject
@property (nonatomic, readonly) BOOL submitTicket;
@end

SWIFT_CLASS("_TtCCC20ZohoDeskPortalAPIKit8ZDPortal21HelpCenterPreferences14Configurations")
@interface Configurations : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCCCC20ZohoDeskPortalAPIKit8ZDPortal21HelpCenterPreferences14Configurations15GoogleAnalytics")
@interface GoogleAnalytics : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull trackerId;
@property (nonatomic, readonly, copy) NSString * _Nonnull domainName;
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull analyticsType;
@end

SWIFT_CLASS("_TtCCCC20ZohoDeskPortalAPIKit8ZDPortal21HelpCenterPreferences14Configurations3Seo")
@interface Seo : NSObject
@property (nonatomic, readonly) BOOL isEnabled;
@property (nonatomic, readonly, copy) NSString * _Nonnull metaKeyWord;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSString * _Nonnull metaDescription;
@end

SWIFT_CLASS("_TtCCC20ZohoDeskPortalAPIKit8ZDPortal21HelpCenterPreferences12ActiveLocale")
@interface ActiveLocale : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull i18nLocaleName;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull locale;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@end

SWIFT_CLASS("_TtC20ZohoDeskPortalAPIKit17ZohoDeskPortalSDK")
@interface ZohoDeskPortalSDK : NSObject
+ (void)initializeWithOrgID:(NSString * _Nonnull)orgID appID:(NSString * _Nonnull)appID dataCenter:(enum ZDPDataCenter)dataCenter;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isUserLoggedIn;)
+ (BOOL)isUserLoggedIn SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface ZohoDeskPortalSDK (SWIFT_EXTENSION(ZohoDeskPortalAPIKit))
+ (void)enableLogs;
+ (void)loginWithJWTToken:(NSString * _Nonnull)identifier onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)signInOnCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)signUpInLanguage:(NSString * _Nonnull)languageCode onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)getUserInformationOnCompletion:(void (^ _Nonnull)(ZDPProfile * _Nullable, NSError * _Nullable))handler;
+ (void)updateUserInformationWith:(NSDictionary<NSString *, NSString *> * _Nonnull)dict onCompletion:(void (^ _Nonnull)(ZDPProfile * _Nullable, NSError * _Nullable))handler;
+ (void)logoutOnCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)clearAllLocalData;
+ (void)getDepartmentsOnCompletion:(void (^ _Nonnull)(NSArray<Department *> * _Nullable, NSError * _Nullable))handler;
+ (void)getProductsInDepartmentID:(NSString * _Nonnull)deptID params:(NSDictionary<NSString *, id> * _Nullable)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPProduct *> * _Nullable, NSError * _Nullable))handler;
+ (void)getContentFrom:(NSString * _Nonnull)url onCompletion:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))handler;
+ (void)syncSettingsOnCompletion:(void (^ _Nonnull)(ZDPSettings * _Nullable, NSError * _Nullable))handler;
+ (void)enablePushNotificationWithDeviceToken:(NSString * _Nonnull)deviceToken isTestDevice:(BOOL)isTestDevice mode:(enum APNSmode)mode;
+ (void)disablePushNotificationsWithDeviceToken:(NSString * _Nonnull)deviceToken mode:(enum APNSmode)mode onCompletion:(void (^ _Nonnull)(BOOL))handler;
+ (void)getContactsByEmail:(NSString * _Nonnull)emailID onCompletion:(void (^ _Nonnull)(ZDPContact * _Nullable, NSError * _Nullable))handler;
+ (void)getContactsByIds:(NSDictionary<NSString *, NSString *> * _Nonnull)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPContact *> * _Nullable, NSError * _Nullable))handler;
+ (void)searchContactsByText:(NSDictionary<NSString *, NSString *> * _Nonnull)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPContact *> * _Nullable, NSError * _Nullable))handler;
+ (void)getAccountsWithText:(NSDictionary<NSString *, NSString *> * _Nonnull)params onCompletion:(void (^ _Nonnull)(NSArray<ZDPAccount *> * _Nullable, NSError * _Nullable))handler;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
